/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package systemvetenskapligaprojektet;
import oru.inf.InfDB; //importeras i alla klasser som vi ska använda
import oru.inf.InfException; //importeras i alla klasser som vi ska använda
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
/**
 *
 * @author limme
 */
public class AllaAvdelningar extends javax.swing.JFrame {
    private InfDB idb;
    private String inloggadAnvandare;
    /**
     * Creates new form TestTable
     */
    public AllaAvdelningar(InfDB idb, String inloggadAnvandare) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        initComponents();        
        fyllTabell();
    }
    
    public void fyllTabell(){
        try{
        String[] kolumnNamn = {"avdid", "namn", "beskrivning", "adress", "epost", "telefon", "stad", "chef"};
        DefaultTableModel allaAvdelningar = new DefaultTableModel(kolumnNamn, 0);
        
        String selectAvdid = "select avdid from avdelning order by(avdid);";
        ArrayList<String> avdid = idb.fetchColumn(selectAvdid);
            if(avdid != null){
                for(String ettID:avdid){
                    String selectInfo = "select * from avdelning where avdid = " + ettID + ";";
                    HashMap<String,String> info = idb.fetchRow(selectInfo);
            
                    Object[] enRad = new Object[kolumnNamn.length];
                    int index = 0;
            
                    for(String enKolumn:kolumnNamn){
                        if(enKolumn.equals("beskrivning")){
                            enRad[index++] = "Se beskrivning";
                        }
                        else if(enKolumn.equals("stad")){
                            String selectStad = 
                            "select namn from stad where sid = (select stad from avdelning where avdid = " + ettID + ");";
                            String stad = idb.fetchSingle(selectStad);
                            enRad[index++] = stad;
                        }
                        else if(enKolumn.equals("chef")){
                            String selectChefFornamn = 
                            "select fornamn from anstalld where aid = (select chef from avdelning where avdid = " + ettID + ");";
                            String chefFornamn = idb.fetchSingle(selectChefFornamn);
                            String selectChefEfternamn = 
                            "select efternamn from anstalld where aid = (select chef from avdelning where avdid = " + ettID + ");";
                            String chefEfternamn = idb.fetchSingle(selectChefEfternamn);
                            String chefFulltNamn = chefFornamn + " " + chefEfternamn;
                            enRad[index++] = chefFulltNamn;
                        }
                        else{
                            enRad[index++] = info.get(enKolumn);}
                    }
                    allaAvdelningar.addRow(enRad);
                }
                tblTest.setModel(allaAvdelningar);
            }
            tblTest.setAutoResizeMode(tblTest.AUTO_RESIZE_OFF);
            TableColumn col = tblTest.getColumnModel().getColumn(0);
            col.setPreferredWidth(100);
            col = tblTest.getColumnModel().getColumn(1);
            col.setPreferredWidth(400);
            col = tblTest.getColumnModel().getColumn(2);
            col.setPreferredWidth(150);
            col = tblTest.getColumnModel().getColumn(3);
            col.setPreferredWidth(150);
            col = tblTest.getColumnModel().getColumn(4);
            col.setPreferredWidth(150);
            col = tblTest.getColumnModel().getColumn(5);
            col.setPreferredWidth(150);
            col = tblTest.getColumnModel().getColumn(6);
            col.setPreferredWidth(150);
            col = tblTest.getColumnModel().getColumn(7);
            col.setPreferredWidth(150);
        }
        catch(InfException ex){
            System.out.println(ex);
        }       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTest = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnTillbaka = new javax.swing.JButton();
        btnLäggTill = new javax.swing.JButton();
        btnRedigera = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblTest.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        tblTest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        tblTest.setEnabled(false);
        tblTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTestMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTest);

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        jLabel1.setText("ALLA AVDELNINGAR");

        btnTillbaka.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        btnLäggTill.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        btnLäggTill.setText("Lägg till ny anställd");
        btnLäggTill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLäggTillActionPerformed(evt);
            }
        });

        btnRedigera.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        btnRedigera.setText("Redigera en avdelning");
        btnRedigera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedigeraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 953, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLäggTill)
                        .addGap(18, 18, 18)
                        .addComponent(btnRedigera)
                        .addGap(566, 566, 566)
                        .addComponent(btnTillbaka)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTillbaka)
                    .addComponent(btnLäggTill)
                    .addComponent(btnRedigera))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblTestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTestMouseClicked
        int column = tblTest.columnAtPoint(evt.getPoint());
        if(column == 2){
            new BeskrivningAvdelningar(idb,inloggadAnvandare).setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_tblTestMouseClicked

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        new MenyAdmin(idb,inloggadAnvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnLäggTillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLäggTillActionPerformed
        new LaggTillAvdelning(idb,inloggadAnvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLäggTillActionPerformed

    private void btnRedigeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedigeraActionPerformed
        new RedigeraAvdelning(idb,inloggadAnvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRedigeraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllaAvdelningar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllaAvdelningar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllaAvdelningar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllaAvdelningar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TestTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLäggTill;
    private javax.swing.JButton btnRedigera;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTest;
    // End of variables declaration//GEN-END:variables
}
