/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package systemvetenskapligaprojektet;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import oru.inf.InfDB; //Ska importeras till alla klasser
import oru.inf.InfException;
/**
 *
 * @author lisas
 */
public class AnsvarProjekt extends javax.swing.JFrame {
    private static InfDB idb;
    private String inloggadAnvandare;
    /**
     * Creates new form AnsvarProjekt
     */
    public AnsvarProjekt(InfDB idb, String inloggadAnvandare) {
        initComponents();
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        fyllTabell();
    }
    
    public void fyllTabell() {
        try {
            String[] kolumnNamn = {"pid", "projektnamn", "beskrivning", "startdatum", "slutdatum", "kostnad", "status", "prioritet", "projektchef", "land"};
            DefaultTableModel allaAnsvarProjekt = new DefaultTableModel(kolumnNamn, 0);

            // Hämta alla projekt-ID
            String selectPid = "SELECT pid FROM projekt WHERE projektchef IN (SELECT aid FROM anstalld WHERE epost = '" + inloggadAnvandare + "');";
            ArrayList<String> pidLista = idb.fetchColumn(selectPid);

            if (pidLista != null) {
                for (String ettPID : pidLista) {
                    String selectInfo = "SELECT pid, projektnamn, beskrivning, startdatum, slutdatum, kostnad, status, prioritet, " +
                            "(SELECT CONCAT(fornamn, ' ', efternamn) FROM anstalld WHERE aid = projektchef) AS projektchef, " +
                            "(SELECT namn FROM land WHERE lid = land) AS land " +
                            "FROM projekt WHERE pid = " + ettPID + ";";
                    ArrayList<HashMap<String, String>> info = idb.fetchRows(selectInfo);

                    Object[] enRad = new Object[kolumnNamn.length];
                    int index = 0;

                    for (String enKolumn : kolumnNamn) {
                        enRad[index++] = info.get(0).get(enKolumn);
                    }

                    allaAnsvarProjekt.addRow(enRad);
                }

                tblAnsvarProjekt.setModel(allaAnsvarProjekt);
            }

            tblAnsvarProjekt.setAutoResizeMode(tblAnsvarProjekt.AUTO_RESIZE_OFF);

            TableColumn col = tblAnsvarProjekt.getColumnModel().getColumn(0);
            col.setPreferredWidth(50);

            col = tblAnsvarProjekt.getColumnModel().getColumn(1);
            col.setPreferredWidth(100);

            col = tblAnsvarProjekt.getColumnModel().getColumn(2);
            col.setPreferredWidth(175);

            col = tblAnsvarProjekt.getColumnModel().getColumn(3);
            col.setPreferredWidth(100);

            col = tblAnsvarProjekt.getColumnModel().getColumn(4);
            col.setPreferredWidth(100);

            col = tblAnsvarProjekt.getColumnModel().getColumn(5);
            col.setPreferredWidth(100);

            col = tblAnsvarProjekt.getColumnModel().getColumn(6);
            col.setPreferredWidth(100);

            col = tblAnsvarProjekt.getColumnModel().getColumn(7);
            col.setPreferredWidth(75);

            col = tblAnsvarProjekt.getColumnModel().getColumn(8);
            col.setPreferredWidth(75);

            col = tblAnsvarProjekt.getColumnModel().getColumn(9);
            col.setPreferredWidth(50);

        } catch (InfException ex) {
            System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAnsvarProjekt = new javax.swing.JTable();
        btnTillbaka = new javax.swing.JButton();
        btnRedigera = new javax.swing.JButton();
        btnPartner = new javax.swing.JButton();
        btnHandlaggare = new javax.swing.JButton();
        btnStatistik = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblAnsvarProjekt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10"
            }
        ));
        jScrollPane1.setViewportView(tblAnsvarProjekt);

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        btnRedigera.setText("Redigera");
        btnRedigera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedigeraActionPerformed(evt);
            }
        });

        btnPartner.setText("Partner");
        btnPartner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartnerActionPerformed(evt);
            }
        });

        btnHandlaggare.setText("Handläggare");
        btnHandlaggare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHandlaggareActionPerformed(evt);
            }
        });

        btnStatistik.setText("Statistik");
        btnStatistik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatistikActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRedigera)
                        .addGap(35, 35, 35)
                        .addComponent(btnPartner)
                        .addGap(38, 38, 38)
                        .addComponent(btnHandlaggare)
                        .addGap(29, 29, 29)
                        .addComponent(btnStatistik)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTillbaka))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTillbaka)
                    .addComponent(btnRedigera)
                    .addComponent(btnPartner)
                    .addComponent(btnHandlaggare)
                    .addComponent(btnStatistik))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        new MinaProjekt(idb, inloggadAnvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnStatistikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatistikActionPerformed
        new AnsvarProjektStatistik(idb, inloggadAnvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnStatistikActionPerformed

    private void btnHandlaggareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHandlaggareActionPerformed
        new AnsvarProjektHandlaggare(idb, inloggadAnvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHandlaggareActionPerformed

    private void btnPartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartnerActionPerformed
        new AnsvarProjektPartner(idb, inloggadAnvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPartnerActionPerformed

    private void btnRedigeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedigeraActionPerformed
        new RedigeraAnsvarProjekt(idb, inloggadAnvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRedigeraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnsvarProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnsvarProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnsvarProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnsvarProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new AnsvarProjekt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHandlaggare;
    private javax.swing.JButton btnPartner;
    private javax.swing.JButton btnRedigera;
    private javax.swing.JButton btnStatistik;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAnsvarProjekt;
    // End of variables declaration//GEN-END:variables
}
