/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package systemvetenskapligaprojektet;
import oru.inf.InfDB; //Ska importeras till alla klasser
import oru.inf.InfException;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
/**
 *
 * @author lisas
 */
public class AnsvarProjektStatistik extends javax.swing.JFrame {
    private static InfDB idb;
    private String inloggadAnvandare;

    /**
     * Creates new form AnsvarProjektStatistik
     */
    public AnsvarProjektStatistik(InfDB idb, String inloggadAnvandare) {
        initComponents();
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        fyllTabell();
    }
    
    public void fyllTabell(){
        try{
            //Skapar en array som lagrar kolumnnamnen.
            String[] kolumnNamn = {"pid", "projektnamn", "kostnad"};
            
             //Skapar en DefaultTableModel som håller kolumnnamnen samt sätter antalet rader till noll.
            DefaultTableModel allaKostnader = new DefaultTableModel(kolumnNamn, 0);
            
            //Hämtar projekt ID från projekt där projektchefen är den inloggade användaren. Dessa projekt ID läggs sedan in i "pidLista".
            String selectPid = "SELECT pid FROM projekt where projektchef in (select aid from anstalld where epost = '" + inloggadAnvandare + "');";
            ArrayList<String> pidLista = idb.fetchColumn(selectPid);
            
            //Om "pisLista" inte är null.
            if(pidLista != null){
                //Skapar en for-each loop som går igenom "pidLista". För varje projekt ID hämtas data om projektet och läggs i en ArrayList av HashMap "Info".
                for (String ettPID : pidLista) {
                String selectInfo = "select pid, projektnamn, kostnad FROM projekt where pid = " + ettPID + ";";
                ArrayList<HashMap<String, String>> info = idb.fetchRows(selectInfo);
                
                //Skapar en array som håller data för en rad i tabellen.
                Object[] enRad = new Object[kolumnNamn.length];
                int index = 0;
                
                //En for-each loop som går igenom varje kolumn i "kolumnNamn" där värdet för "enKolumn" läggs till i "enRad".
                for (String enKolumn : kolumnNamn) {
                        enRad[index++] = info.get(0).get(enKolumn);
                    }
                 //EnRad läggs till i DefaultTableModel.
                allaKostnader.addRow(enRad);
            }
                 //Jtable sätts med data från DefaultTableModel.
                tblStatistik.setModel(allaKostnader);
            }
            tblStatistik.setAutoResizeMode(tblStatistik.AUTO_RESIZE_OFF);
            //Sätter storleken på tabellen.
            TableColumn col = tblStatistik.getColumnModel().getColumn(0);
            col.setPreferredWidth(50);
            col = tblStatistik.getColumnModel().getColumn(1);
            col.setPreferredWidth(100);
            col = tblStatistik.getColumnModel().getColumn(2);
            col.setPreferredWidth(100);
        }
        catch (InfException ex) {
            System.out.println(ex);
    }
}        
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblKostnader = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStatistik = new javax.swing.JTable();
        btnTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblKostnader.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        lblKostnader.setText("KOSTNADER FÖR MINA PROJEKT");

        jScrollPane1.setEnabled(false);

        tblStatistik.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        tblStatistik.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tblStatistik.setEnabled(false);
        jScrollPane1.setViewportView(tblStatistik);

        btnTillbaka.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblKostnader))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnTillbaka)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblKostnader)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnTillbaka)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        new AnsvarProjekt(idb,inloggadAnvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTillbakaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnsvarProjektStatistik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnsvarProjektStatistik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnsvarProjektStatistik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnsvarProjektStatistik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            //    new AnsvarProjektStatistik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblKostnader;
    private javax.swing.JTable tblStatistik;
    // End of variables declaration//GEN-END:variables
}
