/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package systemvetenskapligaprojektet;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author limme
 */
public class BeskrivningHallbarhetsmal extends javax.swing.JFrame {
    private InfDB idb;
    private String inloggadAnvandare;
    /**
     * Creates new form BeskrivningHallbarhetsmal
     */
    public BeskrivningHallbarhetsmal(InfDB idb, String inloggadAnvandare) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        initComponents();
        fyllTabell();
    }

    public void fyllTabell(){
        try{
            
          //Skapar en array som lagrar kolumnnamnen.   
        String[] kolumnNamn = {"hid", "beskrivning"};
        
        //Skapar en DefaultTableModel som håller kolumnnamnen samt sätter antalet rader till noll.
        DefaultTableModel allaHallbarhetsmal = new DefaultTableModel(kolumnNamn, 0);
        
        //Hämtar alla avdelnings ID från avdelning och lägger dessa i en ArrayList(avdid).
        String selectHid = "select hid from hallbarhetsmal order by(hid);";
        ArrayList<String> hid = idb.fetchColumn(selectHid);
        //Om avdid inte är null.
            if(hid != null){
                //Loopar igenom "avdid" och för varje avdelnings ID hämtas id och beskrivning om avdelningen och läggs in i "info".
                for(String ettID:hid){
                    String selectInfo = "select hid,beskrivning from hallbarhetsmal where hid = " + ettID + ";";
                    HashMap<String,String> info = idb.fetchRow(selectInfo);
            
                    //Skapar en array som håller data för en rad i tabellen.
                    Object[] enRad = new Object[kolumnNamn.length];
                    int index = 0;
            
                    //En for-each loop som går igenom varje kolumn i "kolumnNamn" där värdet för "enKolumn" läggs till i "enRad".
                    for(String enKolumn:kolumnNamn){
                        enRad[index++] = info.get(enKolumn);
                    }
                     //EnRad läggs till i DefaultTableModel.
                    allaHallbarhetsmal.addRow(enRad);
                }
                //Jtable sätts med data från DefaultTableModel.
                tblBeskrivning.setModel(allaHallbarhetsmal);
            }
            tblBeskrivning.setAutoResizeMode(tblBeskrivning.AUTO_RESIZE_OFF);
            //Sätter storleken på tabellen.
            TableColumn col = tblBeskrivning.getColumnModel().getColumn(0);
            col.setPreferredWidth(75);
            col = tblBeskrivning.getColumnModel().getColumn(1);
            col.setPreferredWidth(700);
        }
        catch(InfException ex){
            System.out.println(ex);
        }       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblBeskrivning = new javax.swing.JTable();
        lblBeskrivning = new javax.swing.JLabel();
        btnBeskrivning = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblBeskrivning.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        tblBeskrivning.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(tblBeskrivning);

        lblBeskrivning.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        lblBeskrivning.setText("BESKRIVNINGAR FÖR HÅLLBARHETSMÅLEN");

        btnBeskrivning.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        btnBeskrivning.setText("Tillbaka");
        btnBeskrivning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeskrivningActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBeskrivning))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBeskrivning)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblBeskrivning)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addGap(45, 45, 45)
                .addComponent(btnBeskrivning)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBeskrivningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeskrivningActionPerformed
        new Hallbarhetsmal(idb,inloggadAnvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBeskrivningActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BeskrivningHallbarhetsmal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BeskrivningHallbarhetsmal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BeskrivningHallbarhetsmal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BeskrivningHallbarhetsmal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new BeskrivningHallbarhetsmal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBeskrivning;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBeskrivning;
    private javax.swing.JTable tblBeskrivning;
    // End of variables declaration//GEN-END:variables
}
