/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package systemvetenskapligaprojektet;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;

/**
 *
 * @author mejaa
 */
public class laggTillHandlaggare extends javax.swing.JFrame {
    private static InfDB idb;
    private String inloggadAnvandare;
    private int inlagdPidInt;
    private int inlagdAidInt;

    /**
     * Creates new form laggTillHandlaggare
     */
    public laggTillHandlaggare(InfDB idb, String inloggadAnvandare) {
        this.inloggadAnvandare = inloggadAnvandare;
        this.idb = idb;
        initComponents();
        felmeddelandenOsynliga();
    }
    
    private void felmeddelandenOsynliga(){
        lblHandlaggareInfo.setVisible(false);
        tfAid.setVisible(false);
        btnSparaAID.setVisible(false);
        lblOgiltigtAid.setVisible(false);
        lblOgiltigtPid.setVisible(false);
        lblHandlaggareLagtsTillProjekt.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLaggTillHandlaggare = new javax.swing.JLabel();
        lblHandlaggareInfo = new javax.swing.JLabel();
        lblProjektInfo = new javax.swing.JLabel();
        tfAid = new javax.swing.JTextField();
        tfPid = new javax.swing.JTextField();
        btnTillbaka = new javax.swing.JButton();
        btnSparaPID = new javax.swing.JButton();
        lblOgiltigtPid = new javax.swing.JLabel();
        lblOgiltigtAid = new javax.swing.JLabel();
        lblHandlaggareLagtsTillProjekt = new javax.swing.JLabel();
        btnSparaAID = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLaggTillHandlaggare.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblLaggTillHandlaggare.setText("Lägg till handläggare på projekt");

        lblHandlaggareInfo.setText("Skriv in vilken handläggare (aid) du vill lägga till:");

        lblProjektInfo.setText("Skriv in vilket projekt (pid) handläggaren ska läggas till i:");

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        btnSparaPID.setText("Spara");
        btnSparaPID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaPIDActionPerformed(evt);
            }
        });

        lblOgiltigtPid.setText("Ogiltigt projektid");

        lblOgiltigtAid.setText("Ogiltigt anställningsid");

        lblHandlaggareLagtsTillProjekt.setText("Handläggaren har lagts till på projektet");

        btnSparaAID.setText("Spara");
        btnSparaAID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaAIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblOgiltigtAid)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblProjektInfo)
                                    .addComponent(lblHandlaggareInfo)
                                    .addComponent(lblLaggTillHandlaggare))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfPid, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblOgiltigtPid, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(tfAid, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSparaPID)
                            .addComponent(btnSparaAID)
                            .addComponent(btnTillbaka))
                        .addGap(0, 23, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHandlaggareLagtsTillProjekt)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLaggTillHandlaggare, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjektInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSparaPID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOgiltigtPid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHandlaggareInfo)
                    .addComponent(tfAid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSparaAID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOgiltigtAid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(lblHandlaggareLagtsTillProjekt)
                .addGap(18, 18, 18)
                .addComponent(btnTillbaka)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        new AnsvarProjektHandlaggare(idb, inloggadAnvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnSparaPIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaPIDActionPerformed
        try{
            //Hämtar det som lagts in i rutan för Aid och Pid.
            String inlagdPid =tfPid.getText();
            try{
                inlagdPidInt = Integer.parseInt(inlagdPid);
            }
            catch(NumberFormatException ex){
                lblOgiltigtPid.setVisible(true);
            }
            String selectAllaProjekt = "select pid from projekt where projektchef = (select aid from anstalld where epost = '" + inloggadAnvandare + "') order by (pid);";
            ArrayList<String> allaProjekt = idb.fetchColumn(selectAllaProjekt);
            for(String ettProjekt : allaProjekt){
                        if(ettProjekt.equals(inlagdPid)){
                            lblHandlaggareInfo.setVisible(true);
                            tfAid.setVisible(true);
                            btnSparaAID.setVisible(true);
                            break;
                        }
                        else{
                            //Om det inlagda pid inte matchar något av de pid som användaren är projektchef över visas ett felmeddelande.
                            lblOgiltigtPid.setVisible(true);
                        }
            }
            //Hämtar alla aid som är handläggare och lägger det i en ArrayList.

            //Går igenom alla handlaggares aid, om något av dessa matchar det aid som har lagts in av användaren skapas en ArrayList av de pid som användaren är projektchef för.
            
                    //Loppar igenom de pid som användaren är projektchef för, om något av dessa matchar det inlagda pid så läggs det inlagda pid och aid in i databasen.
                    

                            //Om det inlagda pid inte matchar något av de pid som användaren är projektchef över visas ett felmeddelande.


                    //Om det inlagda aid inte matchar något av de aid som är handläggare visas ett felmeddelande.

            
        }
        catch(InfException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnSparaPIDActionPerformed

    private void btnSparaAIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaAIDActionPerformed
        try{
            String inlagdAid = tfAid.getText();
            String inlagdPid =tfPid.getText();
            try{
                inlagdAidInt = Integer.parseInt(inlagdAid);
            }
            catch(NumberFormatException ex){
                lblOgiltigtAid.setVisible(true);
            }
            String selectAllaHandlaggare = "select aid from handlaggare order by (aid);";
            ArrayList<String> allaHandlaggare = idb.fetchColumn(selectAllaHandlaggare);
            for(String enHandlaggare : allaHandlaggare){
                if(enHandlaggare.equals(inlagdAid)){
                    String updateAidProjekt = "insert into ans_proj(pid,aid) values (" + inlagdPidInt + "," + inlagdAidInt + ");";
                    idb.insert(updateAidProjekt);
                    lblHandlaggareLagtsTillProjekt.setVisible(true);
                    break;
                }
                else{
                    //Om det inlagda aid inte matchar något av de aid som är handläggare visas ett felmeddelande.
                    lblOgiltigtAid.setVisible(true);
                }
            }
        }
        catch(InfException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnSparaAIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laggTillHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laggTillHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laggTillHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laggTillHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new laggTillHandlaggare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSparaAID;
    private javax.swing.JButton btnSparaPID;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JLabel lblHandlaggareInfo;
    private javax.swing.JLabel lblHandlaggareLagtsTillProjekt;
    private javax.swing.JLabel lblLaggTillHandlaggare;
    private javax.swing.JLabel lblOgiltigtAid;
    private javax.swing.JLabel lblOgiltigtPid;
    private javax.swing.JLabel lblProjektInfo;
    private javax.swing.JTextField tfAid;
    private javax.swing.JTextField tfPid;
    // End of variables declaration//GEN-END:variables
}
