/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package systemvetenskapligaprojektet;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;

/**
 *
 * @author mejaa
 */
public class laggTillHandlaggare extends javax.swing.JFrame {
    private static InfDB idb;
    private String inloggadAnvandare;

    /**
     * Creates new form laggTillHandlaggare
     */
    public laggTillHandlaggare(InfDB idb, String inloggadAnvandare) {
        this.inloggadAnvandare = inloggadAnvandare;
        this.idb = idb;
        initComponents();
        felmeddelandenOsynliga();
    }
    
    private void felmeddelandenOsynliga(){
        lblOgiltigtAid.setVisible(false);
        lblOgiltigtPid.setVisible(false);
        lblHandlaggareLagtsTillProjekt.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLaggTillHandlaggare = new javax.swing.JLabel();
        lblHandlaggareInfo = new javax.swing.JLabel();
        lblProjektInfo = new javax.swing.JLabel();
        tfAid = new javax.swing.JTextField();
        tfPid = new javax.swing.JTextField();
        btnTillbaka = new javax.swing.JButton();
        btnSpara = new javax.swing.JButton();
        lblOgiltigtPid = new javax.swing.JLabel();
        lblOgiltigtAid = new javax.swing.JLabel();
        lblHandlaggareLagtsTillProjekt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLaggTillHandlaggare.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblLaggTillHandlaggare.setText("Lägg till handläggare på projekt");

        lblHandlaggareInfo.setText("Skriv in vilken handläggare (aid) du vill lägga till:");

        lblProjektInfo.setText("Skriv in vilket projekt (pid) handläggaren ska läggas till i:");

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        btnSpara.setText("Spara");
        btnSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaActionPerformed(evt);
            }
        });

        lblOgiltigtPid.setText("Ogiltigt projektid");

        lblOgiltigtAid.setText("Ogiltigt anställningsid");

        lblHandlaggareLagtsTillProjekt.setText("Handläggaren har lagts till på projektet");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblLaggTillHandlaggare)
                        .addGap(118, 118, 118))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnSpara)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnTillbaka))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblHandlaggareInfo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfAid, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblOgiltigtAid, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblProjektInfo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblOgiltigtPid)
                                            .addComponent(tfPid, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(lblHandlaggareLagtsTillProjekt))
                        .addContainerGap(14, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLaggTillHandlaggare, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHandlaggareInfo)
                    .addComponent(tfAid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOgiltigtAid)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjektInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOgiltigtPid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(lblHandlaggareLagtsTillProjekt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTillbaka)
                    .addComponent(btnSpara))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        new AnsvarProjektHandlaggare(idb, inloggadAnvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
        try{
            //Hämtar det som lagts in i rutan för Aid och Pid.
            String inlagdAid = tfAid.getText();
            String inlagdPid =tfPid.getText();
            //Hämtar alla aid som är handläggare och lägger det i en ArrayList.
            String selectAllaHandlaggare = "select aid from handlaggare order by (aid);";
            ArrayList<String> allaHandlaggare = idb.fetchColumn(selectAllaHandlaggare);
            //Går igenom alla handlaggares aid, om något av dessa matchar det aid som har lagts in av användaren skapas en ArrayList av de pid som användaren är projektchef för.
            System.out.println("Inlagt Aid: " + inlagdAid);
            for(String enHandlaggare : allaHandlaggare){
                System.out.println("Alla Handläggare Aid: " + enHandlaggare);
                if(enHandlaggare.equals(inlagdAid)){
                    String selectAllaProjekt ="select pid from projekt where projektchef = (select aid from anstalld where epost = '" + inloggadAnvandare + "') order by (pid);";
                    ArrayList<String> allaProjekt = idb.fetchColumn(selectAllaProjekt);
                    //Loppar igenom de pid som användaren är projektchef för, om något av dessa matchar det inlagda pid så läggs det inlagda pid och aid in i databasen.
                    for(String ettProjekt : allaProjekt){
                        if(ettProjekt.equals(inlagdPid)){
                            int inlagdAidInt = Integer.parseInt(inlagdAid);
                            int inlagdPidInt = Integer.parseInt(inlagdPid);
                            String updateAidProjekt = "insert into ans_proj(pid,aid) values (" + inlagdAidInt + "," + inlagdPidInt + ");";
                            idb.insert(updateAidProjekt);
                            lblHandlaggareLagtsTillProjekt.setVisible(true);
                        }
                        else{
                            //Om det inlagda pid inte matchar något av de pid som användaren är projektchef över visas ett felmeddelande.
                                lblOgiltigtPid.setVisible(true);
                        }
                    }
                }
                else{
                    //Om det inlagda aid inte matchar något av de aid som är handläggare visas ett felmeddelande.
                        lblOgiltigtAid.setVisible(true);
                }
            
            }
            
        }
        catch(InfException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnSparaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laggTillHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laggTillHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laggTillHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laggTillHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new laggTillHandlaggare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSpara;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JLabel lblHandlaggareInfo;
    private javax.swing.JLabel lblHandlaggareLagtsTillProjekt;
    private javax.swing.JLabel lblLaggTillHandlaggare;
    private javax.swing.JLabel lblOgiltigtAid;
    private javax.swing.JLabel lblOgiltigtPid;
    private javax.swing.JLabel lblProjektInfo;
    private javax.swing.JTextField tfAid;
    private javax.swing.JTextField tfPid;
    // End of variables declaration//GEN-END:variables
}
