/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package systemvetenskapligaprojektet;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.math.BigDecimal;
import java.util.ArrayList;
/**
 *
 * @author iftinserar
 */
public class LaggTillProjekt extends javax.swing.JFrame {
    private static InfDB idb;
    private String inloggadAnvandare;
    private int pid;
    private int projektchef;
    private int land;
    private Validering validera;

    /**
     * Skapar nytt formulär för att lägga till ett projekt.
     */
    public LaggTillProjekt(InfDB idb, String inloggadAnvandare) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        initComponents();
        lblFelmeddelandeProjektID.setVisible(false);
        lblFelmeddelandeStartdatum.setVisible(false);
        lblFelmeddelandeSlutdatum.setVisible(false);
        lblFelmeddelandeKostnad.setVisible(false);
        lblFelmeddelandeProjektchef.setVisible(false);
        lblFelmeddelandeLand.setVisible(false);
        lblLyckat.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSpara = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblProjektID = new javax.swing.JLabel();
        lblProjektNamn = new javax.swing.JLabel();
        lblBeskrivning = new javax.swing.JLabel();
        lblStartdatum = new javax.swing.JLabel();
        lblSlutdatum = new javax.swing.JLabel();
        lblKostnad = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblPrioritet = new javax.swing.JLabel();
        lblProjektchef = new javax.swing.JLabel();
        lblLand = new javax.swing.JLabel();
        lblFelmeddelandeProjektID = new javax.swing.JLabel();
        tfProjektID = new javax.swing.JTextField();
        tfProjektNamn = new javax.swing.JTextField();
        tfBeskrivning = new javax.swing.JTextField();
        tfStartdatum = new javax.swing.JTextField();
        tfSlutdatum = new javax.swing.JTextField();
        tfKostnad = new javax.swing.JTextField();
        tfProjektchef = new javax.swing.JTextField();
        tfLand = new javax.swing.JTextField();
        lblFelmeddelandeStartdatum = new javax.swing.JLabel();
        lblFelmeddelandeSlutdatum = new javax.swing.JLabel();
        lblFelmeddelandeProjektchef = new javax.swing.JLabel();
        lblFelmeddelandeLand = new javax.swing.JLabel();
        lblFelmeddelandeKostnad = new javax.swing.JLabel();
        comboStatus = new javax.swing.JComboBox<>();
        comboPrioritet = new javax.swing.JComboBox<>();
        lblLyckat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSpara.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        btnSpara.setText("Spara");
        btnSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaActionPerformed(evt);
            }
        });

        btnTillbaka.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        jLabel1.setText("LÄGG TILL ETT PROJEKT");

        lblProjektID.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblProjektID.setText("ID");

        lblProjektNamn.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblProjektNamn.setText("Namn");

        lblBeskrivning.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblBeskrivning.setText("Beskrivning");

        lblStartdatum.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblStartdatum.setText("Startdatum");

        lblSlutdatum.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblSlutdatum.setText("Slutdatum");

        lblKostnad.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblKostnad.setText("Kostnad");

        lblStatus.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblStatus.setText("Status");

        lblPrioritet.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblPrioritet.setText("Prioritet");

        lblProjektchef.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblProjektchef.setText("Projektchef");

        lblLand.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblLand.setText("Land");

        lblFelmeddelandeProjektID.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 2, 12)); // NOI18N
        lblFelmeddelandeProjektID.setForeground(new java.awt.Color(255, 0, 0));
        lblFelmeddelandeProjektID.setText("ID:t existerar redan");

        tfProjektID.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        tfProjektID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfProjektIDActionPerformed(evt);
            }
        });

        tfProjektNamn.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N

        tfBeskrivning.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N

        tfStartdatum.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N

        tfSlutdatum.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N

        tfKostnad.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N

        tfProjektchef.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N

        tfLand.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N

        lblFelmeddelandeStartdatum.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 2, 12)); // NOI18N
        lblFelmeddelandeStartdatum.setForeground(new java.awt.Color(255, 0, 0));
        lblFelmeddelandeStartdatum.setText("Använd korrekt datumformat: YYYY-MM-DD");

        lblFelmeddelandeSlutdatum.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 2, 12)); // NOI18N
        lblFelmeddelandeSlutdatum.setForeground(new java.awt.Color(255, 0, 0));
        lblFelmeddelandeSlutdatum.setText("Använd korrekt datumformat: YYYY-MM-DD");

        lblFelmeddelandeProjektchef.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 2, 12)); // NOI18N
        lblFelmeddelandeProjektchef.setForeground(new java.awt.Color(255, 0, 0));
        lblFelmeddelandeProjektchef.setText("Välj ett existerande anställningsID");

        lblFelmeddelandeLand.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 2, 12)); // NOI18N
        lblFelmeddelandeLand.setForeground(new java.awt.Color(255, 0, 0));
        lblFelmeddelandeLand.setText("Välj ett existerande landsID");

        lblFelmeddelandeKostnad.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 2, 12)); // NOI18N
        lblFelmeddelandeKostnad.setForeground(new java.awt.Color(255, 0, 0));
        lblFelmeddelandeKostnad.setText("Felaktigt format! Max tio siffror exklusive två decimaler");

        comboStatus.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pågående", "Planerad", "Avslutad" }));

        comboPrioritet.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        comboPrioritet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hög", "Medel", "Låg" }));

        lblLyckat.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 2, 12)); // NOI18N
        lblLyckat.setForeground(new java.awt.Color(0, 153, 0));
        lblLyckat.setText("Den anställda har lagts till!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBeskrivning)
                            .addComponent(lblStartdatum)
                            .addComponent(lblKostnad)
                            .addComponent(lblStatus)
                            .addComponent(lblPrioritet)
                            .addComponent(lblProjektchef))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfBeskrivning)
                            .addComponent(lblFelmeddelandeStartdatum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfStartdatum)
                            .addComponent(tfProjektID)
                            .addComponent(tfKostnad)
                            .addComponent(tfProjektNamn)
                            .addComponent(lblFelmeddelandeSlutdatum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfProjektchef)
                            .addComponent(comboPrioritet, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfLand)
                            .addComponent(comboStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLyckat, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSpara)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnTillbaka))))
                            .addComponent(tfSlutdatum, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                            .addComponent(lblFelmeddelandeKostnad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFelmeddelandeProjektID)
                                    .addComponent(lblFelmeddelandeProjektchef, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFelmeddelandeLand, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jLabel1)
                    .addComponent(lblLand)
                    .addComponent(lblProjektID)
                    .addComponent(lblProjektNamn)
                    .addComponent(lblSlutdatum))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjektID)
                    .addComponent(tfProjektID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(lblFelmeddelandeProjektID)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjektNamn)
                    .addComponent(tfProjektNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBeskrivning)
                    .addComponent(tfBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStartdatum)
                    .addComponent(tfStartdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(lblFelmeddelandeStartdatum)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSlutdatum)
                    .addComponent(tfSlutdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(lblFelmeddelandeSlutdatum)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKostnad)
                    .addComponent(tfKostnad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(lblFelmeddelandeKostnad)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboPrioritet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrioritet))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjektchef)
                    .addComponent(tfProjektchef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(lblFelmeddelandeProjektchef)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLand)
                    .addComponent(tfLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFelmeddelandeLand)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTillbaka)
                    .addComponent(btnSpara))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLyckat)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfProjektIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfProjektIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfProjektIDActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        new AllaProjekt(idb, inloggadAnvandare).setVisible(true);
        this.setVisible(false);    // TODO add your handling code here:
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
        try {
            lblFelmeddelandeProjektID.setVisible(false);
            lblFelmeddelandeStartdatum.setVisible(false);
            lblFelmeddelandeSlutdatum.setVisible(false);
            lblFelmeddelandeKostnad.setVisible(false);
            lblFelmeddelandeProjektchef.setVisible(false);
            lblFelmeddelandeLand.setVisible(false);
            lblLyckat.setVisible(false);
            
            String textProjektID = tfProjektID.getText();
            String projektNamn = tfProjektNamn.getText();
            String beskrivning = tfBeskrivning.getText();
            String status = (String) comboStatus.getSelectedItem();
            String startDatum = tfStartdatum.getText();
            String slutDatum = tfSlutdatum.getText();
            String textKostnad = tfKostnad.getText();
            String prioritet = (String) comboPrioritet.getSelectedItem();
            String textProjektchef = tfProjektchef.getText();
            String textLand = tfLand.getText();
            
            if(validera.valideringDatum(startDatum) && validera.valideringDatum(slutDatum)){
                try {
                    pid = Integer.parseInt(textProjektID);
                } 
                catch (NumberFormatException ex) {
                    lblFelmeddelandeProjektID.setVisible(true);
                }
                try {
                    projektchef = Integer.parseInt(textProjektchef);
                } 
                catch (NumberFormatException ex) {
                    lblFelmeddelandeProjektchef.setVisible(true);
                }
                try {
                    land = Integer.parseInt(textLand);
                } 
                catch (NumberFormatException ex) {
                    lblFelmeddelandeLand.setVisible(true);
                }
                
                BigDecimal kostnad;
                try{
                    kostnad = new BigDecimal(textKostnad);

                    //Kontrollera (12, 2)
                    if (kostnad.precision() - kostnad.scale() > 10 || kostnad.scale() > 2) {
                        lblFelmeddelandeKostnad.setVisible(true);
                        return;
                    }
                }
                catch(NumberFormatException ex){
                    lblFelmeddelandeKostnad.setVisible(true);
                    return;
                }

                // Kontrollera om Projekt ID redan finns
                    String checkaPID = "select pid from projekt where pid = " + pid + ";";
                    String ettPID = idb.fetchSingle(checkaPID);
                // Kontrollera om AID är en handläggare
                    String checkaEnProjektchef = "select aid from handlaggare where aid = " + projektchef + ";";
                    String enProjektChef = idb.fetchSingle(checkaEnProjektchef);
                // Kontrollera om landet finns
                    String checkaEttLand = "select lid from land where lid = " + land + ";";
                    String ettLand = idb.fetchSingle(checkaEttLand);
                    
                    if (ettPID != null) { 
                        lblFelmeddelandeProjektID.setVisible(true);
                    }                   
                    if (enProjektChef == null) { 
                        lblFelmeddelandeProjektchef.setVisible(true);
                    }
                    if (ettLand == null) { 
                        lblFelmeddelandeLand.setVisible(true);
                    }
                    else {
                        // Om Projekt ID inte finns, lägg till det nya projektet
                        String insertNyProjekt = "insert into projekt (pid, projektnamn, beskrivning, startdatum, slutdatum, kostnad, status, prioritet, projektchef, land) values (" 
                            + pid + ", '" + projektNamn + "', '" + beskrivning + "', '" + startDatum + "', '" 
                            + slutDatum + "', " + kostnad + ", '" + status + "', '" + prioritet + "', " + projektchef + ", " 
                            + land + ");";
                        idb.insert(insertNyProjekt);
                        lblLyckat.setVisible(true);    
                    }
                
            }
            else{
                if(!validera.valideringDatum(startDatum)){
                    lblFelmeddelandeStartdatum.setVisible(true);
                }
                else if(!validera.valideringDatum(slutDatum)){
                    lblFelmeddelandeSlutdatum.setVisible(true);
                }
                else{
                    lblFelmeddelandeStartdatum.setVisible(true);
                    lblFelmeddelandeSlutdatum.setVisible(true);
                }
            }
        } 
        catch (InfException ex) {
            System.out.println(ex);
        }    // TODO add your handling code here:
    }//GEN-LAST:event_btnSparaActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new LaggTillProjekt(idb, "projektchef").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSpara;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JComboBox<String> comboPrioritet;
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBeskrivning;
    private javax.swing.JLabel lblFelmeddelandeKostnad;
    private javax.swing.JLabel lblFelmeddelandeLand;
    private javax.swing.JLabel lblFelmeddelandeProjektID;
    private javax.swing.JLabel lblFelmeddelandeProjektchef;
    private javax.swing.JLabel lblFelmeddelandeSlutdatum;
    private javax.swing.JLabel lblFelmeddelandeStartdatum;
    private javax.swing.JLabel lblKostnad;
    private javax.swing.JLabel lblLand;
    private javax.swing.JLabel lblLyckat;
    private javax.swing.JLabel lblPrioritet;
    private javax.swing.JLabel lblProjektID;
    private javax.swing.JLabel lblProjektNamn;
    private javax.swing.JLabel lblProjektchef;
    private javax.swing.JLabel lblSlutdatum;
    private javax.swing.JLabel lblStartdatum;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextField tfBeskrivning;
    private javax.swing.JTextField tfKostnad;
    private javax.swing.JTextField tfLand;
    private javax.swing.JTextField tfProjektID;
    private javax.swing.JTextField tfProjektNamn;
    private javax.swing.JTextField tfProjektchef;
    private javax.swing.JTextField tfSlutdatum;
    private javax.swing.JTextField tfStartdatum;
    // End of variables declaration//GEN-END:variables
}
