/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package systemvetenskapligaprojektet;
import oru.inf.InfDB; //importeras i alla klasser som vi ska använda
import oru.inf.InfException; //importeras i alla klasser som vi ska använda
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;


/**
 *
 * @author limme
 */
public class MinAvdelning extends javax.swing.JFrame {

    private static InfDB idb;
    private String inloggadAnvandare;
    /**
     * Creates new form MinAvdelning
     */
    public MinAvdelning(InfDB idb, String inloggadAnvandare) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        initComponents();
        laggInData();
    }
    
    private void laggInData(){
       
                try{
                    String selectAvdid = "select avdelning from anstalld where aid = (select aid from anstalld where epost = '" + inloggadAnvandare + "');";
                    String avdid = idb.fetchSingle(selectAvdid);
                    tfId.setText(avdid);
                    
                    String selectNamn = "select namn from avdelning where avdid = (select avdelning from anstalld where epost = '" + inloggadAnvandare + "');";
                    String namn = idb.fetchSingle(selectNamn);
                    tfNamn.setText(namn);
                    
                    tfBeskrivning.setText("Klicka här för att se beskrivning!");
                    
                    String selectAdress = "select adress from avdelning where avdid = (select avdelning from anstalld where epost = '" + inloggadAnvandare + "');";
                    String adress = idb.fetchSingle(selectAdress);
                    tfAdress.setText(adress);
                    
                    String selectEpost = "select epost from avdelning where avdid = (select avdelning from anstalld where epost = '" + inloggadAnvandare + "');";
                    String epost = idb.fetchSingle(selectEpost);
                    tfEpost.setText(epost);
                    
                    String selectTelefonnummer = "select telefon from avdelning where avdid = (select avdelning from anstalld where epost = '" + inloggadAnvandare + "');";
                    String telefonnummer = idb.fetchSingle(selectTelefonnummer);
                    tfTelefon.setText(telefonnummer);
                    
                    String selectStad = "select namn from stad where sid = (select stad from avdelning where avdid = (select avdelning from anstalld where epost = '" + inloggadAnvandare + "'));";
                    String stad = idb.fetchSingle(selectStad);
                    tfStad.setText(stad);
                    
                    String selectAvdelningschefF = "select fornamn from anstalld where aid = (select chef from avdelning where avdid = (select avdelning from anstalld where epost = '" + inloggadAnvandare + "'));";
                    String selectAvdelningschefE = "select efternamn from anstalld where aid = (select chef from avdelning where avdid = (select avdelning from anstalld where epost = '" + inloggadAnvandare + "'));";
                    String avdelningschefF = idb.fetchSingle(selectAvdelningschefF);
                    String avdelningschefE = idb.fetchSingle(selectAvdelningschefE);
                    String avdelningschef = avdelningschefF + " " + avdelningschefE;
                    tfAvdelningschef.setText(avdelningschef);

                    
                }
                catch(InfException ex){
                System.out.println(ex);
                
                
                
    }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblNamn = new javax.swing.JLabel();
        lblBeskrivning = new javax.swing.JLabel();
        lblAdress = new javax.swing.JLabel();
        lblEpost = new javax.swing.JLabel();
        lblTelefon = new javax.swing.JLabel();
        lblStad = new javax.swing.JLabel();
        lblAvdelningschef = new javax.swing.JLabel();
        tfTelefon = new javax.swing.JTextField();
        tfStad = new javax.swing.JTextField();
        tfAvdelningschef = new javax.swing.JTextField();
        tfEpost = new javax.swing.JTextField();
        tfAdress = new javax.swing.JTextField();
        tfNamn = new javax.swing.JTextField();
        tfId = new javax.swing.JTextField();
        tfBeskrivning = new javax.swing.JTextField();
        btnTillbaka = new javax.swing.JButton();
        btnAnställda = new javax.swing.JButton();
        btnProjekt = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jTextField2.setText("jTextField1");

        jTextField9.setText("jTextField1");
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        jLabel1.setText("MIN AVDELNING");

        lblId.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblId.setText("ID");

        lblNamn.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblNamn.setText("Namn");

        lblBeskrivning.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblBeskrivning.setText("Beskrivning");

        lblAdress.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblAdress.setText("Adress");

        lblEpost.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblEpost.setText("Epost");

        lblTelefon.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblTelefon.setText("Telefon");

        lblStad.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblStad.setText("Stad");

        lblAvdelningschef.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblAvdelningschef.setText("Avdelningschef");

        tfTelefon.setEditable(false);
        tfTelefon.setBackground(new java.awt.Color(255, 255, 255));
        tfTelefon.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        tfTelefon.setText("jTextField1");

        tfStad.setEditable(false);
        tfStad.setBackground(new java.awt.Color(255, 255, 255));
        tfStad.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        tfStad.setText("jTextField1");

        tfAvdelningschef.setEditable(false);
        tfAvdelningschef.setBackground(new java.awt.Color(255, 255, 255));
        tfAvdelningschef.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        tfAvdelningschef.setText("jTextField1");

        tfEpost.setEditable(false);
        tfEpost.setBackground(new java.awt.Color(255, 255, 255));
        tfEpost.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        tfEpost.setText("jTextField1");

        tfAdress.setEditable(false);
        tfAdress.setBackground(new java.awt.Color(255, 255, 255));
        tfAdress.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        tfAdress.setText("jTextField1");

        tfNamn.setEditable(false);
        tfNamn.setBackground(new java.awt.Color(255, 255, 255));
        tfNamn.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        tfNamn.setText("jTextField1");
        tfNamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamnActionPerformed(evt);
            }
        });

        tfId.setEditable(false);
        tfId.setBackground(new java.awt.Color(255, 255, 255));
        tfId.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        tfId.setText("jTextField1");
        tfId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdActionPerformed(evt);
            }
        });

        tfBeskrivning.setEditable(false);
        tfBeskrivning.setBackground(new java.awt.Color(255, 255, 255));
        tfBeskrivning.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        tfBeskrivning.setText("jTextField1");
        tfBeskrivning.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfBeskrivningMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfBeskrivningMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfBeskrivningMouseExited(evt);
            }
        });

        btnTillbaka.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        btnAnställda.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        btnAnställda.setText("Se anställda");
        btnAnställda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnställdaActionPerformed(evt);
            }
        });

        btnProjekt.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        btnProjekt.setText("Se projekt");
        btnProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProjektActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAvdelningschef)
                            .addComponent(lblId)
                            .addComponent(lblNamn)
                            .addComponent(lblBeskrivning)
                            .addComponent(lblAdress)
                            .addComponent(lblEpost)
                            .addComponent(lblTelefon)
                            .addComponent(lblStad))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNamn, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                            .addComponent(tfAdress)
                            .addComponent(tfEpost)
                            .addComponent(tfTelefon)
                            .addComponent(tfStad)
                            .addComponent(tfAvdelningschef)
                            .addComponent(tfBeskrivning)
                            .addComponent(tfId)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAnställda)
                                .addGap(18, 18, 18)
                                .addComponent(btnProjekt)))
                        .addGap(191, 191, 191)
                        .addComponent(btnTillbaka)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblId))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNamn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBeskrivning))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdress))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEpost))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefon))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfStad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStad))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvdelningschef)
                    .addComponent(tfAvdelningschef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTillbaka)
                    .addComponent(btnAnställda)
                    .addComponent(btnProjekt))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamnActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void tfIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdActionPerformed

    private void tfBeskrivningMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfBeskrivningMouseEntered
       //tfBeskrivning.setLayout(null);
       //tfBeskrivning.setPreferredSize(new Dimension(30, 600));
       //tfBeskrivning.revalidate();
       //tfBeskrivning.repaint();
    }//GEN-LAST:event_tfBeskrivningMouseEntered

    private void tfBeskrivningMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfBeskrivningMouseExited
       //tfBeskrivning.setPreferredSize(new Dimension(22, 356));
       //tfBeskrivning.revalidate();
       //tfBeskrivning.repaint();
    }//GEN-LAST:event_tfBeskrivningMouseExited

    private void btnAnställdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnställdaActionPerformed
        new AvdelningensAnstallda(idb, inloggadAnvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAnställdaActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        new MenyHandlaggare(idb, inloggadAnvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProjektActionPerformed
        new AvdelningensProjekt(idb, inloggadAnvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnProjektActionPerformed

    private void tfBeskrivningMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfBeskrivningMouseClicked
        if(evt.getSource() == tfBeskrivning){
            new AvdelningsBeskrivning(idb,inloggadAnvandare).setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_tfBeskrivningMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MinAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MinAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MinAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MinAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MinAvdelning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnställda;
    private javax.swing.JButton btnProjekt;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel lblAvdelningschef;
    private javax.swing.JLabel lblBeskrivning;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JLabel lblStad;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JTextField tfAdress;
    private javax.swing.JTextField tfAvdelningschef;
    private javax.swing.JTextField tfBeskrivning;
    private javax.swing.JTextField tfEpost;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfNamn;
    private javax.swing.JTextField tfStad;
    private javax.swing.JTextField tfTelefon;
    // End of variables declaration//GEN-END:variables
}
