/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package systemvetenskapligaprojektet;
import java.util.ArrayList;
import java.util.HashMap;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
/**
 *
 * @author limme
 */
public class RedigeraAvdelning extends javax.swing.JFrame {
    private InfDB idb;
    private String inloggadAnvandare;
    private int avdid;
    private int stadsID;
    private int chefsID;
    private String stad;
    private String chef;
    
    /**
     * Creates new form RedigeraAvdelning
     */
    public RedigeraAvdelning(InfDB idb, String inloggadAnvandare) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        initComponents();
        lblFelmeddelandeStad.setVisible(false);
        lblFelmeddelandeAvdelningschef.setVisible(false);
        lblFelmeddelandeEpost.setVisible(false);
        lblFelmeddelandeTel.setVisible(false);
        lblLyckat.setVisible(false);
        fyllComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRedigeraAvdelning = new javax.swing.JLabel();
        lblNamn = new javax.swing.JLabel();
        lblBeskrivning = new javax.swing.JLabel();
        lblAdress = new javax.swing.JLabel();
        lblEpost = new javax.swing.JLabel();
        lblTelefon = new javax.swing.JLabel();
        lblStad = new javax.swing.JLabel();
        lblChef = new javax.swing.JLabel();
        tfBeskrivning = new javax.swing.JTextField();
        tfNamn = new javax.swing.JTextField();
        tfAdress = new javax.swing.JTextField();
        tfEpost = new javax.swing.JTextField();
        tfTelefon = new javax.swing.JTextField();
        tfStad = new javax.swing.JTextField();
        tfChef = new javax.swing.JTextField();
        btnTillbaka = new javax.swing.JButton();
        btnSpara = new javax.swing.JButton();
        lblFelmeddelandeStad = new javax.swing.JLabel();
        lblFelmeddelandeAvdelningschef = new javax.swing.JLabel();
        lblFelmeddelandeEpost = new javax.swing.JLabel();
        lblFelmeddelandeTel = new javax.swing.JLabel();
        lblProjektID = new javax.swing.JLabel();
        ComboRedigeraAvdelning = new javax.swing.JComboBox<>();
        lblLyckat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblRedigeraAvdelning.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        lblRedigeraAvdelning.setText("REDIGERA UPPGIFTER");

        lblNamn.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblNamn.setText("Namn");

        lblBeskrivning.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblBeskrivning.setText("Beskrivning");

        lblAdress.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblAdress.setText("Adress");

        lblEpost.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblEpost.setText("Epost");

        lblTelefon.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblTelefon.setText("Telefon");

        lblStad.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblStad.setText("Stad");

        lblChef.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblChef.setText("Avdelningschef");

        btnTillbaka.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        btnSpara.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        btnSpara.setText("Spara");
        btnSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaActionPerformed(evt);
            }
        });

        lblFelmeddelandeStad.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 2, 12)); // NOI18N
        lblFelmeddelandeStad.setForeground(new java.awt.Color(255, 0, 0));
        lblFelmeddelandeStad.setText("Välj ett existerande stadsID");

        lblFelmeddelandeAvdelningschef.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 2, 12)); // NOI18N
        lblFelmeddelandeAvdelningschef.setForeground(new java.awt.Color(255, 0, 0));
        lblFelmeddelandeAvdelningschef.setText("Välj ett existerande anställningsID");

        lblFelmeddelandeEpost.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 2, 12)); // NOI18N
        lblFelmeddelandeEpost.setForeground(new java.awt.Color(255, 0, 0));
        lblFelmeddelandeEpost.setText("Fyll i en giltig epostadress: XXX@XXX.XXX");

        lblFelmeddelandeTel.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 2, 12)); // NOI18N
        lblFelmeddelandeTel.setForeground(new java.awt.Color(255, 0, 0));
        lblFelmeddelandeTel.setText("Fyll i ett giltigt telefonnummer: XXXXXXXXXX");

        lblProjektID.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblProjektID.setText("Välj projekt att redigera");

        ComboRedigeraAvdelning.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3 - Kommunikation och medvetenhet om digitala rättigheter." }));
        ComboRedigeraAvdelning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboRedigeraAvdelningActionPerformed(evt);
            }
        });

        lblLyckat.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 2, 12)); // NOI18N
        lblLyckat.setForeground(new java.awt.Color(0, 153, 0));
        lblLyckat.setText("Ändringarna har sparats!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRedigeraAvdelning)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblProjektID)
                        .addGap(35, 35, 35)
                        .addComponent(ComboRedigeraAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBeskrivning)
                            .addComponent(lblNamn)
                            .addComponent(lblAdress)
                            .addComponent(lblEpost)
                            .addComponent(lblTelefon)
                            .addComponent(lblStad)
                            .addComponent(lblChef, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 294, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLyckat, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSpara)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnTillbaka))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfBeskrivning)
                                    .addComponent(tfNamn)
                                    .addComponent(tfAdress)
                                    .addComponent(tfEpost)
                                    .addComponent(tfTelefon)
                                    .addComponent(tfStad)
                                    .addComponent(tfChef)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblFelmeddelandeAvdelningschef, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblFelmeddelandeStad, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblFelmeddelandeTel, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblFelmeddelandeEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblRedigeraAvdelning)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjektID)
                    .addComponent(ComboRedigeraAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamn)
                    .addComponent(tfNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBeskrivning)
                    .addComponent(tfBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdress)
                    .addComponent(tfAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEpost)
                    .addComponent(tfEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(lblFelmeddelandeEpost)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefon)
                    .addComponent(tfTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(lblFelmeddelandeTel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStad)
                    .addComponent(tfStad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(lblFelmeddelandeStad)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChef)
                    .addComponent(tfChef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(lblFelmeddelandeAvdelningschef)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTillbaka)
                    .addComponent(btnSpara))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLyckat)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        new AllaAvdelningar(idb,inloggadAnvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
        boolean hasError = false;
        boolean hittad = false;
        try{
            if(!hasError){
                try{
                    hittad = false;
                    stad = tfStad.getText();
                    String selectAllaStader = "select sid from stad;";
                    ArrayList<String> allaStader = idb.fetchColumn(selectAllaStader);
                    if(!stad.isEmpty()){
                        stadsID = Integer.parseInt(stad);
                    }
                    for(String enStad:allaStader){
                        int ettStadsID = Integer.parseInt(enStad);
                        if(ettStadsID==stadsID || stad.isEmpty()){
                            hittad = true;
                            lblFelmeddelandeStad.setVisible(false);
                            break;
                        }
                    }
                    if(!hittad){
                        lblFelmeddelandeStad.setVisible(true);
                        hasError = true;
                    }
                }
                catch(NumberFormatException ex){
                    lblFelmeddelandeStad.setVisible(true);
                    hasError = true;
                }
            }
            if(!hasError){
                try{
                    hittad = false;
                    chef = tfChef.getText();
                    String selectAllaHandlaggare = "select aid from handlaggare;";
                    ArrayList<String> allaHandlaggare = idb.fetchColumn(selectAllaHandlaggare);
                    if(!chef.isEmpty()){
                        chefsID = Integer.parseInt(chef);
                    }
                    for(String enHandlaggare:allaHandlaggare){
                        int ettHandlaggarID = Integer.parseInt(enHandlaggare);
                        if(ettHandlaggarID==chefsID || chef.isEmpty()){
                            hittad = true;
                            lblFelmeddelandeAvdelningschef.setVisible(false);
                            break;
                        }
                    }
                    if(!hittad){
                        lblFelmeddelandeAvdelningschef.setVisible(true);
                        hasError = true;
                    }
                }
                catch(NumberFormatException ex){
                    lblFelmeddelandeAvdelningschef.setVisible(true);
                    hasError = true;
                }
            }
            if(!hasError){
                String namn = tfNamn.getText();
                String beskrivning = tfBeskrivning.getText();
                String adress = tfAdress.getText();
                String epost = tfEpost.getText(); //Kolla så att det verkligen är en epost-adress!
                String telefon = tfTelefon.getText();
                String selectEnAvdelning = "select * from avdelning where avdid = " + avdid + ";";
                HashMap<String,String> enAvdelning = idb.fetchRow(selectEnAvdelning);
                String[] enRad = new String[enAvdelning.size()];
                    for(String ettAttribut:enAvdelning.keySet()){
                        switch (ettAttribut){
                            case "avdid":
                                enRad[0] = enAvdelning.get("avdid");
                            case "namn":
                                enRad[1] = enAvdelning.get("namn");
                            case "beskrivning":
                                enRad[2] = enAvdelning.get("beskrivning");
                            case "adress":
                                enRad[3] = enAvdelning.get("adress");
                            case "epost":
                                enRad[4] = enAvdelning.get("epost");
                            case "telefon":
                                enRad[5] = enAvdelning.get("telefon");
                            case "stad":
                                enRad[6] = enAvdelning.get("stad");
                            case "chef":
                                enRad[7] = enAvdelning.get("chef");
                        }
                    }
                    if(namn.isEmpty()){
                        namn = enRad[1];
                    }
                    if(beskrivning.isEmpty()){
                        beskrivning = enRad[2];
                    }
                    if(adress.isEmpty()){
                        adress = enRad[3];
                    }
                    if(epost.isEmpty()){
                        epost = enRad[4];
                    }
                    if(telefon.isEmpty()){
                        telefon = enRad[5];
                    }   
                    if(stad.isEmpty()){
                        stad = enRad[6];
                        stadsID = Integer.parseInt(stad);
                    }
                    if(chef.isEmpty()){
                        chef = enRad[7];
                        chefsID = Integer.parseInt(chef);
                    }
                //Hämta från databasen och tilldela variablerna värden från den så de inte är tomma när de uppdateras!!
                String updateAvdelning = "update avdelning set namn = '" + namn + "', beskrivning = '" + beskrivning + "', adress = '" + adress + "', epost = '" 
                        + epost + "', telefon = '" + telefon + "', stad = " + stadsID + ", chef = " + chefsID + " where avdid = " + avdid + ";";
                idb.update(updateAvdelning);
                lblLyckat.setVisible(true);
            }
        }
        catch(InfException ex){ //Catch InfExceptions?
                System.out.println(ex);
        }
    }//GEN-LAST:event_btnSparaActionPerformed

    private void ComboRedigeraAvdelningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboRedigeraAvdelningActionPerformed
        fyllTextfields();
    }//GEN-LAST:event_ComboRedigeraAvdelningActionPerformed

    public void fyllComboBox(){
        try{
            String selectAvdid = "select avdid, namn from avdelning order by (avdid);";
            
            ArrayList<HashMap<String, String>> allaAvdid = idb.fetchRows(selectAvdid);
            
            ComboRedigeraAvdelning.removeAllItems();
            ComboRedigeraAvdelning.addItem("Välj avdelning");
            
            for (HashMap<String, String> avdelning : allaAvdid) {
                String avdelningsInfo = avdelning.get("avdid") + " - " + avdelning.get("namn");
                ComboRedigeraAvdelning.addItem(avdelningsInfo);
            }
        }
        catch (InfException e) {
            JOptionPane.showMessageDialog(this, "Kunde inte fylla avdelningar: " + e.getMessage());
        }
    }
   
    private void fyllTextfields(){
        ComboRedigeraAvdelning.addActionListener(evt -> {
            String avdelning = ComboRedigeraAvdelning.getSelectedItem().toString();
            
            if (!avdelning.equals("Välj avdelning")) {
                String textValdAvdelning = "Välj avdelning: " + avdelning;
                System.out.println(textValdAvdelning);
                // Regex för att matcha siffran direkt efter "Välj avdelning: "
                Pattern pattern = Pattern.compile("Välj avdelning: (\\d+)");
                Matcher matcher = pattern.matcher(textValdAvdelning);
                
                if (matcher.find()) {
                    // Extrahera den första matchade gruppen
                    String enAvdelning = matcher.group(1);
                    avdid = Integer.parseInt(enAvdelning);
                    
                    System.out.println("Numret är: " + avdid);
                } else {
                    System.out.println("Ingen match hittades."); 
                }
            } 
        });
        try{
            String selectInfo = "select * from avdelning where avdid = " + avdid + ";";
            System.out.println(selectInfo);
            ArrayList<HashMap<String, String>> info = idb.fetchRows(selectInfo);
            
            for(HashMap<String, String> enRad:info){
                for(String ettAttribut:enRad.keySet()){
                    switch(ettAttribut){
                        case "namn":
                            tfNamn.setText(enRad.get(ettAttribut)); 
                            break;
                        case "beskrivning":
                            tfBeskrivning.setText(enRad.get(ettAttribut));
                            break;
                        case "adress":
                            tfAdress.setText(enRad.get(ettAttribut));
                            break;
                        case "epost":
                            tfEpost.setText(enRad.get(ettAttribut));
                            break;
                        case "telefon":
                            tfTelefon.setText(enRad.get(ettAttribut));
                            break;
                        case "stad":
                            tfStad.setText(enRad.get(ettAttribut));
                            break;
                        case "chef":
                            tfChef.setText(enRad.get(ettAttribut));
                            break;
                    }
                }
            }
        }
        catch(InfException ex){
            System.out.println(ex); 
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RedigeraAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RedigeraAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RedigeraAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RedigeraAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new RedigeraAvdelning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboRedigeraAvdelning;
    private javax.swing.JButton btnSpara;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel lblBeskrivning;
    private javax.swing.JLabel lblChef;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblFelmeddelandeAvdelningschef;
    private javax.swing.JLabel lblFelmeddelandeEpost;
    private javax.swing.JLabel lblFelmeddelandeStad;
    private javax.swing.JLabel lblFelmeddelandeTel;
    private javax.swing.JLabel lblLyckat;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JLabel lblProjektID;
    private javax.swing.JLabel lblRedigeraAvdelning;
    private javax.swing.JLabel lblStad;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JTextField tfAdress;
    private javax.swing.JTextField tfBeskrivning;
    private javax.swing.JTextField tfChef;
    private javax.swing.JTextField tfEpost;
    private javax.swing.JTextField tfNamn;
    private javax.swing.JTextField tfStad;
    private javax.swing.JTextField tfTelefon;
    // End of variables declaration//GEN-END:variables
}
