/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package systemvetenskapligaprojektet;
import java.util.ArrayList;
import oru.inf.InfDB; //Ska importeras till alla klasser
import oru.inf.InfException;
import java.math.BigDecimal;
import java.util.HashMap;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
/**
 *
 * @author lisas
 */
public class RedigeraAnsvarProjekt extends javax.swing.JFrame {
    private static InfDB idb;
    private String inloggadAnvandare;
    private double enKostnad;
    private int projektchef;
    private int land;
    private String projektID;
    private int ettProjektID;
    private Validering validera;
    /**
     * Creates new form RedigeraAnsvarProjekt
     */
    public RedigeraAnsvarProjekt(InfDB idb, String inloggadAnvandare) {
        initComponents();
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        lblFelStartdatum.setVisible(false);
        lblFelSlutdatum.setVisible(false);
        lblFelKostnad.setVisible(false);
        lblFelProjektchef.setVisible(false);
        lblFelLand.setVisible(false);
        lblLyckat.setVisible(false);
        fyllComboBox();
    }
    
    private void fyllComboBox(){
        try{
        
        //Hämta projektID från projektchefen som är inloggad
        String selectPid = "SELECT pid, projektnamn FROM projekt where projektchef in (select aid from anstalld where epost = '" + inloggadAnvandare + "');";
        
        ArrayList<HashMap<String, String>> allaPid = idb.fetchRows(selectPid);
        
        ComboRedigeraProjekt.removeAllItems();
        ComboRedigeraProjekt.addItem("Välj projekt");
        
        for (HashMap<String, String> projekt : allaPid) {
                String projektInfo = projekt.get("pid") + " - " + projekt.get("projektnamn");
                ComboRedigeraProjekt.addItem(projektInfo);
            }
        }
        catch (InfException e) {
            JOptionPane.showMessageDialog(this, "Kunde inte fylla kopplade partners: " + e.getMessage());
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTillbaka = new javax.swing.JButton();
        btnSpara = new javax.swing.JButton();
        lblRedigeraProjektet = new javax.swing.JLabel();
        lblProjektnamn = new javax.swing.JLabel();
        lblBeskrivning = new javax.swing.JLabel();
        lblStartdatum = new javax.swing.JLabel();
        lblSlutdatum = new javax.swing.JLabel();
        lblKostnad = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblPrioritet = new javax.swing.JLabel();
        lblProjektchef = new javax.swing.JLabel();
        lblLand = new javax.swing.JLabel();
        tfProjektnamn = new javax.swing.JTextField();
        tfBeskrivning = new javax.swing.JTextField();
        tfStartdatum = new javax.swing.JTextField();
        tfSlutdatum = new javax.swing.JTextField();
        tfKostnad = new javax.swing.JTextField();
        tfProjektchef = new javax.swing.JTextField();
        tfLand = new javax.swing.JTextField();
        lblFelStartdatum = new javax.swing.JLabel();
        lblFelSlutdatum = new javax.swing.JLabel();
        lblFelKostnad = new javax.swing.JLabel();
        lblFelProjektchef = new javax.swing.JLabel();
        lblFelLand = new javax.swing.JLabel();
        ComboRedigeraProjekt = new javax.swing.JComboBox<>();
        comboStatus = new javax.swing.JComboBox<>();
        comboPrioritet = new javax.swing.JComboBox<>();
        lblProjektID = new javax.swing.JLabel();
        lblLyckat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTillbaka.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        btnSpara.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        btnSpara.setText("Spara");
        btnSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaActionPerformed(evt);
            }
        });

        lblRedigeraProjektet.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        lblRedigeraProjektet.setText("REDIGERA UPPGIFTER");

        lblProjektnamn.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblProjektnamn.setText("Projektnamn");

        lblBeskrivning.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblBeskrivning.setText("Beskrivning");

        lblStartdatum.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblStartdatum.setText("Startdatum");

        lblSlutdatum.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblSlutdatum.setText("Slutdatum");

        lblKostnad.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblKostnad.setText("Kostnad");

        lblStatus.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblStatus.setText("Status");

        lblPrioritet.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblPrioritet.setText("Prioritet");

        lblProjektchef.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblProjektchef.setText("Projektchef");

        lblLand.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblLand.setText("Land");

        lblFelStartdatum.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 2, 12)); // NOI18N
        lblFelStartdatum.setForeground(new java.awt.Color(255, 0, 0));
        lblFelStartdatum.setText("Använd korrekt datumformat: YYYY-MM-DD");

        lblFelSlutdatum.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 2, 12)); // NOI18N
        lblFelSlutdatum.setForeground(new java.awt.Color(255, 0, 0));
        lblFelSlutdatum.setText("Använd korrekt datumformat: YYYY-MM-DD");

        lblFelKostnad.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 2, 12)); // NOI18N
        lblFelKostnad.setForeground(new java.awt.Color(255, 0, 0));
        lblFelKostnad.setText("Använd korrekt format: Max 10 siffror");

        lblFelProjektchef.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 2, 12)); // NOI18N
        lblFelProjektchef.setForeground(new java.awt.Color(255, 0, 0));
        lblFelProjektchef.setText("Välj ett existerande anställningsID");

        lblFelLand.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 2, 12)); // NOI18N
        lblFelLand.setForeground(new java.awt.Color(255, 0, 0));
        lblFelLand.setText("Välj ett existerande landsID");

        ComboRedigeraProjekt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboRedigeraProjekt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComboRedigeraProjektMouseClicked(evt);
            }
        });
        ComboRedigeraProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboRedigeraProjektActionPerformed(evt);
            }
        });

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pågående", "Planerat", "Avslutad" }));

        comboPrioritet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hög", "Medel", "Låg" }));

        lblProjektID.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblProjektID.setText("Välj projekt att redigera");

        lblLyckat.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 2, 12)); // NOI18N
        lblLyckat.setForeground(new java.awt.Color(0, 153, 0));
        lblLyckat.setText("Ändringarna har sparats!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProjektID)
                            .addComponent(lblProjektnamn)
                            .addComponent(lblBeskrivning)
                            .addComponent(lblStartdatum)
                            .addComponent(lblSlutdatum)
                            .addComponent(lblKostnad)
                            .addComponent(lblStatus)
                            .addComponent(lblPrioritet, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProjektchef)
                            .addComponent(lblLand))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFelStartdatum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFelSlutdatum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfKostnad)
                            .addComponent(tfProjektchef)
                            .addComponent(tfLand)
                            .addComponent(tfProjektnamn)
                            .addComponent(tfBeskrivning)
                            .addComponent(tfStartdatum)
                            .addComponent(tfSlutdatum)
                            .addComponent(ComboRedigeraProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFelProjektchef, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFelLand, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(comboPrioritet, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboStatus, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblFelKostnad, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRedigeraProjektet)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblLyckat, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnSpara)
                            .addGap(18, 18, 18)
                            .addComponent(btnTillbaka))))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblRedigeraProjektet)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjektID)
                    .addComponent(ComboRedigeraProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjektnamn)
                    .addComponent(tfProjektnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBeskrivning)
                    .addComponent(tfBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStartdatum)
                    .addComponent(tfStartdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(lblFelStartdatum)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSlutdatum)
                    .addComponent(tfSlutdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(lblFelSlutdatum)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKostnad)
                    .addComponent(tfKostnad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(lblFelKostnad)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(comboPrioritet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrioritet)
                    .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjektchef)
                    .addComponent(tfProjektchef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(lblFelProjektchef)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLand)
                    .addComponent(tfLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(lblFelLand)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSpara)
                    .addComponent(btnTillbaka))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLyckat)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        new AnsvarProjekt(idb, inloggadAnvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
        boolean hasError = false;
        boolean hittad = false;
        lblFelStartdatum.setVisible(false);
        lblFelSlutdatum.setVisible(false);
        lblFelKostnad.setVisible(false);
        lblFelProjektchef.setVisible(false);
        lblFelLand.setVisible(false);

        try{
            if(!hasError){
                try{
                    String projektnamn = tfProjektnamn.getText();
                    String beskrivning = tfBeskrivning.getText();
                    String startdatum = tfStartdatum.getText();
                    String slutdatum = tfSlutdatum.getText();
                    String textKostnad = tfKostnad.getText();
                    String textProjektchef = tfProjektchef.getText();
                    String textLand = tfLand.getText();
                    String status = (String) comboStatus.getSelectedItem();
                    String prioritet = (String) comboPrioritet.getSelectedItem();
                    
                    if(validera.valideringDatum(startdatum) && validera.valideringDatum(slutdatum)){
                        if(!hasError){
                            try{
                                textProjektchef = tfProjektchef.getText();
                                projektchef = Integer.parseInt(textProjektchef);
                            }
                            catch(NumberFormatException ex){
                                lblFelProjektchef.setVisible(true);
                                hasError = true;
                            } 
                        }                 
                        if(!hasError){
                            try{
                                textLand = tfLand.getText();
                                land = Integer.parseInt(textLand);
                            }

                            catch(NumberFormatException ex){
                                lblFelLand.setVisible(true);
                                hasError = true;
                            }
                        } 
                        if(!hasError){
                            String selectProjektchef = "select aid from handlaggare where aid = " + projektchef + ";";
                            String enProjektchef = idb.fetchSingle(selectProjektchef);
                            String selectLand = "select lid from land where lid = " + land + ";";
                            String ettLand = idb.fetchSingle(selectLand);
                            
                            if(enProjektchef == null){
                                lblFelProjektchef.setVisible(true);
                            }
                            if(ettLand == null){
                                lblFelLand.setVisible(true);
                            }
                            BigDecimal kostnad;
                                try{
                                    kostnad = new BigDecimal(textKostnad);

                                    //Kontrollera (12, 2)
                                    if (kostnad.precision() - kostnad.scale() > 10 || kostnad.scale() > 2) {
                                        lblFelKostnad.setVisible(true);
                                        return;
                                    }
                                }
                                catch (NumberFormatException ex) {
                                    lblFelKostnad.setVisible(true);
                                    return;
                                }
                                String selectAnsvarProjekt = "select * from projekt where pid = " + ettProjektID + ";";
                                HashMap<String, String> ettAnsvarProjekt = idb.fetchRow(selectAnsvarProjekt);
                                String enRad[] = new String[ettAnsvarProjekt.size()];
                                for(String ettAttribut:ettAnsvarProjekt.keySet()){
                                    switch(ettAttribut){
                                        case "pid":
                                            enRad[0] = ettAnsvarProjekt.get("pid");
                                            break;
                                        case "projektnamn":
                                            enRad[1] = ettAnsvarProjekt.get("projektnamn");
                                            break;
                                        case "beskrivning":
                                            enRad[2] = ettAnsvarProjekt.get("beskrivning");
                                            break;
                                        case "startdatum":
                                            enRad[3] = ettAnsvarProjekt.get("startdatum");
                                            break;
                                        case "slutdatum":
                                            enRad[4] = ettAnsvarProjekt.get("slutdatum");
                                            break;
                                        case "kostnad":
                                            enRad[5] = ettAnsvarProjekt.get("kostnad");
                                            break;
                                        case "projektchef":
                                            enRad[8] = ettAnsvarProjekt.get("projektchef");
                                            break;
                                        case "land":
                                            enRad[9] = ettAnsvarProjekt.get("land");
                                            break;
                                    }
                                }
                                if(projektnamn.isEmpty()){
                                    projektnamn = enRad[1];
                                }
                                if(beskrivning.isEmpty()){
                                   beskrivning = enRad[2];
                                }
                                if(startdatum.isEmpty()){
                                   startdatum = enRad[3];
                                }
                                if(slutdatum.isEmpty()){
                                   slutdatum = enRad[4];
                                }
                                if(textKostnad.isEmpty()){
                                   textKostnad = enRad[5];
                                }
                                if(textProjektchef.isEmpty()){
                                   textProjektchef = enRad[8];     
                                }  
                                if(textLand.isEmpty()){
                                   textLand = enRad[9];     
                                } 
                                try{
                                    String updateAnsvarProjekt = "update projekt set projektnamn = '" + projektnamn + "', beskrivning = '" + beskrivning + "', startdatum = '" + startdatum + "', slutdatum = '" + slutdatum + "', kostnad = " + kostnad + ", status = '" + status + "', prioritet = '" + prioritet + "', projektchef = " + projektchef + ", land = " + land + " where pid = " + ettProjektID + ";";
                                    System.out.println(updateAnsvarProjekt);
                                    idb.update(updateAnsvarProjekt);
                                    lblLyckat.setVisible(true);
                                }
                                catch(InfException ex){
                                    System.out.println(ex);
                                }
                        }
                    }
                    else{
                        if(!validera.valideringDatum(startdatum)){
                            lblFelStartdatum.setVisible(true);
                        }
                        else if(!validera.valideringDatum(slutdatum)){
                            lblFelSlutdatum.setVisible(true);
                        }
                        else{
                            lblFelStartdatum.setVisible(true);
                            lblFelSlutdatum.setVisible(true);
                        }
                    }
                }
                catch(InfException ex){ 
                    System.out.println(ex);
                }
            }
        }
        catch(NumberFormatException ex){ 
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnSparaActionPerformed


    
    private void fyllTextfields(){
        ComboRedigeraProjekt.addActionListener(evt -> {
            //Hämtar datan i comboboxen som valdes
            String projekt = ComboRedigeraProjekt.getSelectedItem().toString();
            System.out.println(projekt);
            //Om comboboxen inte är vald på "Välj projekt"
            if (!projekt.equals("Välj projekt")) {
                // Regex för att matcha siffran direkt efter
                Pattern pattern = Pattern.compile("(\\d+)");
                Matcher matcher = pattern.matcher(projekt);
                // Kontrollera om mönstret hittades
                if (matcher.find()) {
                    // Extrahera den första matchade gruppen
                    String ettProjekt = matcher.group(1);
                    ettProjektID = Integer.parseInt(ettProjekt);
                    
                    System.out.println("Numret är: " + ettProjektID);
                } 
                else{
                    System.out.println("Ingen match hittades."); 
                }
            } 
        });
        try{
            String selectInfo = "select * from projekt where pid = " + ettProjektID + ";";
            System.out.println(selectInfo);
            ArrayList<HashMap<String, String>> info = idb.fetchRows(selectInfo);
            
            for(HashMap<String, String> enRad:info){
                for(String ettAttribut:enRad.keySet()){
                    switch(ettAttribut){
                        case "projektnamn":
                            tfProjektnamn.setText(enRad.get(ettAttribut)); 
                            break;
                        case "beskrivning":
                            tfBeskrivning.setText(enRad.get(ettAttribut));
                            break;
                        case "startdatum":
                            tfStartdatum.setText(enRad.get(ettAttribut));
                            break;
                        case "slutdatum":
                            tfSlutdatum.setText(enRad.get(ettAttribut));
                            break;
                        case "kostnad":
                            tfKostnad.setText(enRad.get(ettAttribut));
                            break;
                        case "projektchef":
                            tfProjektchef.setText(enRad.get(ettAttribut));
                            break;
                        case "land":
                            tfLand.setText(enRad.get(ettAttribut));
                            break;
                    }
                }
            }
        }
        catch(InfException ex){
            System.out.println(ex);
        }
    }
    
    private void ComboRedigeraProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboRedigeraProjektActionPerformed
         fyllTextfields();
    }//GEN-LAST:event_ComboRedigeraProjektActionPerformed

    private void ComboRedigeraProjektMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboRedigeraProjektMouseClicked
        

        
        //int valtProjekt = Integer.parseInt(valtPid[0]);
        //return valtProjekt;
    }//GEN-LAST:event_ComboRedigeraProjektMouseClicked
 
 
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RedigeraAnsvarProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RedigeraAnsvarProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RedigeraAnsvarProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RedigeraAnsvarProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            //    new RedigeraAnsvarProjekt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboRedigeraProjekt;
    private javax.swing.JButton btnSpara;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JComboBox<String> comboPrioritet;
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JLabel lblBeskrivning;
    private javax.swing.JLabel lblFelKostnad;
    private javax.swing.JLabel lblFelLand;
    private javax.swing.JLabel lblFelProjektchef;
    private javax.swing.JLabel lblFelSlutdatum;
    private javax.swing.JLabel lblFelStartdatum;
    private javax.swing.JLabel lblKostnad;
    private javax.swing.JLabel lblLand;
    private javax.swing.JLabel lblLyckat;
    private javax.swing.JLabel lblPrioritet;
    private javax.swing.JLabel lblProjektID;
    private javax.swing.JLabel lblProjektchef;
    private javax.swing.JLabel lblProjektnamn;
    private javax.swing.JLabel lblRedigeraProjektet;
    private javax.swing.JLabel lblSlutdatum;
    private javax.swing.JLabel lblStartdatum;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextField tfBeskrivning;
    private javax.swing.JTextField tfKostnad;
    private javax.swing.JTextField tfLand;
    private javax.swing.JTextField tfProjektchef;
    private javax.swing.JTextField tfProjektnamn;
    private javax.swing.JTextField tfSlutdatum;
    private javax.swing.JTextField tfStartdatum;
    // End of variables declaration//GEN-END:variables
}

