/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package systemvetenskapligaprojektet;
import java.util.ArrayList;
import oru.inf.InfDB; //Ska importeras till alla klasser
import oru.inf.InfException;
import java.math.BigDecimal;
import java.util.HashMap;
/**
 *
 * @author lisas
 */
public class RedigeraAnsvarProjekt extends javax.swing.JFrame {
    private static InfDB idb;
    private String inloggadAnvandare;
    private int pid;
    private double enKostnad;
    private int projektchef;
    private int land;
    /**
     * Creates new form RedigeraAnsvarProjekt
     */
    public RedigeraAnsvarProjekt(InfDB idb, String inloggadAnvandare) {
        initComponents();
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        lblFelID.setVisible(false);
        lblFelStartdatum.setVisible(false);
        lblFelSlutdatum.setVisible(false);
        lblFelKostnad.setVisible(false);
        lblFelStatus.setVisible(false);
        lblFelPrioritet.setVisible(false);
        lblFelProjektchef.setVisible(false);
        lblFelLand.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTillbaka = new javax.swing.JButton();
        btnSpara = new javax.swing.JButton();
        lblRedigeraProjektet = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        lblProjektnamn = new javax.swing.JLabel();
        lblBeskrivning = new javax.swing.JLabel();
        lblStartdatum = new javax.swing.JLabel();
        lblSlutdatum = new javax.swing.JLabel();
        lblKostnad = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblPrioritet = new javax.swing.JLabel();
        lblProjektchef = new javax.swing.JLabel();
        lblLand = new javax.swing.JLabel();
        tfProjektnamn = new javax.swing.JTextField();
        tfBeskrivning = new javax.swing.JTextField();
        tfStartdatum = new javax.swing.JTextField();
        tfSlutdatum = new javax.swing.JTextField();
        tfKostnad = new javax.swing.JTextField();
        tfStatus = new javax.swing.JTextField();
        tfPrioritet = new javax.swing.JTextField();
        tfProjektchef = new javax.swing.JTextField();
        tfLand = new javax.swing.JTextField();
        lblFelStartdatum = new javax.swing.JLabel();
        lblFelSlutdatum = new javax.swing.JLabel();
        lblFelKostnad = new javax.swing.JLabel();
        lblFelStatus = new javax.swing.JLabel();
        lblFelPrioritet = new javax.swing.JLabel();
        lblFelProjektchef = new javax.swing.JLabel();
        lblFelLand = new javax.swing.JLabel();
        lblFelID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        btnSpara.setText("Spara");
        btnSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaActionPerformed(evt);
            }
        });

        lblRedigeraProjektet.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRedigeraProjektet.setText("Redigera projektets uppgifter");

        lblID.setText("ID");

        lblProjektnamn.setText("Projektnamn");

        lblBeskrivning.setText("Beskrivning");

        lblStartdatum.setText("Startdatum");

        lblSlutdatum.setText("Slutdatum");

        lblKostnad.setText("Kostnad");

        lblStatus.setText("Status");

        lblPrioritet.setText("Prioritet");

        lblProjektchef.setText("Projektchef");

        lblLand.setText("Land");

        lblFelStartdatum.setText("Felaktigt datumformat!");

        lblFelSlutdatum.setText("Felaktigt datumformat!");

        lblFelKostnad.setText("Felaktigt format!");

        lblFelStatus.setText("Ange giltig status");

        lblFelPrioritet.setText("Ange giltig prioritet");

        lblFelProjektchef.setText("Ange giltigt projektchefID");

        lblFelLand.setText("Ange giltigt landID");

        lblFelID.setText("Ange giltigt projektID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblLand, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblProjektchef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPrioritet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblKostnad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSlutdatum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblStartdatum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBeskrivning, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblProjektnamn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSpara, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTillbaka)
                                .addGap(81, 81, 81))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfProjektnamn, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                    .addComponent(tfBeskrivning)
                                    .addComponent(tfStartdatum)
                                    .addComponent(tfSlutdatum)
                                    .addComponent(tfKostnad)
                                    .addComponent(tfStatus)
                                    .addComponent(tfPrioritet)
                                    .addComponent(tfProjektchef)
                                    .addComponent(tfLand))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFelID)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblRedigeraProjektet)
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblFelStartdatum)
                                    .addComponent(lblFelSlutdatum)
                                    .addComponent(lblFelKostnad)
                                    .addComponent(lblFelStatus)
                                    .addComponent(lblFelPrioritet)
                                    .addComponent(lblFelProjektchef)
                                    .addComponent(lblFelLand))))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRedigeraProjektet)
                    .addComponent(lblID)
                    .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFelID)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjektnamn)
                    .addComponent(tfProjektnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBeskrivning)
                    .addComponent(tfBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStartdatum)
                    .addComponent(tfStartdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFelStartdatum))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSlutdatum)
                    .addComponent(tfSlutdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFelSlutdatum))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKostnad)
                    .addComponent(tfKostnad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFelKostnad))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(tfStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFelStatus))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrioritet)
                    .addComponent(tfPrioritet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFelPrioritet))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjektchef)
                    .addComponent(tfProjektchef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFelProjektchef))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLand)
                    .addComponent(tfLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFelLand))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTillbaka)
                    .addComponent(btnSpara))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        new AnsvarProjekt(idb, inloggadAnvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
        boolean hasError = false;
        boolean hittad = false;
        try{
            try{
                String textPID = tfID.getText();
                pid = Integer.parseInt(textPID);
                
                String selectPid = "select pid from projekt where projektchef in (select aid from anstalld where epost = '" + inloggadAnvandare + "');";
                ArrayList<String> allaPid = idb.fetchColumn(selectPid);
                    for(String ettPid:allaPid){
                        int ettID = Integer.parseInt(ettPid);
                        
                        if(ettID == pid){
                        hittad = true;
                        lblFelID.setVisible(false);
                        break;
                    }
                }
                if(!hittad){ 
                    lblFelID.setVisible(true);
                    hasError = true;
                }
            } 
            catch(NumberFormatException ex){
                lblFelID.setVisible(true);
                hasError = true;
            }
                try{
                    String textProjektchef = tfProjektchef.getText();
                    projektchef = Integer.parseInt(textProjektchef);
                }
                
                catch(NumberFormatException ex){
                    lblFelProjektchef.setVisible(true);
                    hasError = true;
                }
                
                try{
                    String textLand = tfLand.getText();
                    land = Integer.parseInt(textLand);
                }
                
                catch(NumberFormatException ex){
                    lblFelLand.setVisible(true);
                    hasError = true;
                }
            
            if(!hasError){
                try{
                    String projektnamn = tfProjektnamn.getText();
                    String beskrivning = tfBeskrivning.getText();
                    String startdatum = tfStartdatum.getText();
                    String slutdatum = tfSlutdatum.getText();
                    String textKostnad = tfKostnad.getText();
                    String status = tfStatus.getText();
                    String prioritet = tfPrioritet.getText();
                    String textProjektchef = tfProjektchef.getText();
                    String textLand = tfLand.getText();
                    
                    
                    BigDecimal kostnad;
                        try{
                            kostnad = new BigDecimal(textKostnad);
                
                            //Kontrollera (13, 4)
                            if(kostnad.precision() > 12 || kostnad.scale() > 2){
                                throw new NumberFormatException();
                            }
                        }
                        catch(NumberFormatException ex){
                            lblFelKostnad.setVisible(true);
                            return;
                        }
                        String selectAnsvarProjekt = "select * from projekt where pid = " + pid + ";";
                        HashMap<String, String> ettAnsvarProjekt = idb.fetchRow(selectAnsvarProjekt);
                        String enRad[] = new String[ettAnsvarProjekt.size()];
                        for(String ettAttribut:ettAnsvarProjekt.keySet()){
                            switch(ettAttribut){
                                case "pid":
                                    enRad[0] = ettAnsvarProjekt.get("pid");
                                case "projektnamn":
                                    enRad[1] = ettAnsvarProjekt.get("projektnamn"); 
                                case "beskrivning":
                                    enRad[2] = ettAnsvarProjekt.get("beskrivning");
                                case "startdatum":
                                    enRad[3] = ettAnsvarProjekt.get("startdatum");
                                case "slutdatum":
                                    enRad[4] = ettAnsvarProjekt.get("slutdatum");
                                case "kostnad":
                                    enRad[5] = ettAnsvarProjekt.get("kostnad");                   
                                case "status":
                                    enRad[6] = ettAnsvarProjekt.get("status");
                                case "prioritet":
                                    enRad[7] = ettAnsvarProjekt.get("status");
                                case "projektchef":
                                    enRad[8] = ettAnsvarProjekt.get("status");
                                case "land":
                                    enRad[9] = ettAnsvarProjekt.get("status");
                        }
                    }
                    if(projektnamn.isEmpty()){
                        projektnamn = enRad[1];
                    }
                    if(beskrivning.isEmpty()){
                       beskrivning = enRad[2];
                    }
                    if(startdatum.isEmpty()){
                       startdatum = enRad[3];
                    }
                    if(slutdatum.isEmpty()){
                       slutdatum = enRad[4];
                    }
                    if(textKostnad.isEmpty()){
                       textKostnad = enRad[5];
                    }
                    if(status.isEmpty()){
                       status = enRad[6];     
                    }
                    if(prioritet.isEmpty()){
                       prioritet = enRad[7];     
                    }  
                    if(textProjektchef.isEmpty()){
                       textProjektchef = enRad[8];     
                    }  
                    if(textLand.isEmpty()){
                       textLand = enRad[9];     
                    } 
                    
                String updateAnsvarProjekt = "update projekt set projektnamn = '" + projektnamn + "', beskrivning = '" + beskrivning + "', startdatum = '" + startdatum + "', slutdatum = '" + slutdatum + "', kostnad = " + kostnad + ", status = '" + status + "', prioritet = '" + prioritet + "', projektchef = " + projektchef + "', stad = " + land + " where pid = " + pid + ";";
                idb.update(updateAnsvarProjekt);
                new AnsvarProjekt(idb,inloggadAnvandare).setVisible(true);
                this.setVisible(false);
                }
                catch(InfException ex){ 
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_btnSparaActionPerformed
    catch(InfException ex){ //Catch InfExceptions?
        System.out.println(ex);
    }
}  
 
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RedigeraAnsvarProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RedigeraAnsvarProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RedigeraAnsvarProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RedigeraAnsvarProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            //    new RedigeraAnsvarProjekt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSpara;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JLabel lblBeskrivning;
    private javax.swing.JLabel lblFelID;
    private javax.swing.JLabel lblFelKostnad;
    private javax.swing.JLabel lblFelLand;
    private javax.swing.JLabel lblFelPrioritet;
    private javax.swing.JLabel lblFelProjektchef;
    private javax.swing.JLabel lblFelSlutdatum;
    private javax.swing.JLabel lblFelStartdatum;
    private javax.swing.JLabel lblFelStatus;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblKostnad;
    private javax.swing.JLabel lblLand;
    private javax.swing.JLabel lblPrioritet;
    private javax.swing.JLabel lblProjektchef;
    private javax.swing.JLabel lblProjektnamn;
    private javax.swing.JLabel lblRedigeraProjektet;
    private javax.swing.JLabel lblSlutdatum;
    private javax.swing.JLabel lblStartdatum;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextField tfBeskrivning;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfKostnad;
    private javax.swing.JTextField tfLand;
    private javax.swing.JTextField tfPrioritet;
    private javax.swing.JTextField tfProjektchef;
    private javax.swing.JTextField tfProjektnamn;
    private javax.swing.JTextField tfSlutdatum;
    private javax.swing.JTextField tfStartdatum;
    private javax.swing.JTextField tfStatus;
    // End of variables declaration//GEN-END:variables
}
