/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package systemvetenskapligaprojektet;
import java.util.ArrayList;
import java.util.HashMap;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
/**
 *
 * @author limme
 */
public class RedigeraLand extends javax.swing.JFrame {
    private static InfDB idb;
    private String inloggadAnvandare;
    private int lid;
    private double enValuta;
    /**
     * Creates new form RedigeraLand
     */
    public RedigeraLand(InfDB idb, String inloggadAnvandare) {
        this.inloggadAnvandare = inloggadAnvandare;
        this.idb = idb;
        initComponents();
        lblValutaFel.setVisible(false);
        lblLyckat1.setVisible(false);
        lblFelmeddelande.setVisible(false);
        fyllComboBox();
    }
    
       public void fyllComboBox(){
        try{
            String selectLid = "select lid, namn from land order by (lid);";
            
            ArrayList<HashMap<String, String>> allaLid = idb.fetchRows(selectLid);
            
            ComboValjLandID.removeAllItems();
            ComboValjLandID.addItem("Välj land");
            
            for (HashMap<String, String> land : allaLid) {
                String landsInfo = land.get("lid") + " - " + land.get("namn");
                ComboValjLandID.addItem(landsInfo);
            }
        }
        catch (InfException e) {
            JOptionPane.showMessageDialog(this, "Kunde inte fylla länder: " + e.getMessage());
        }
    }
    
    //Fyll textfälten med landdata
    private void fyllTextfields(){
        ComboValjLandID.addActionListener(evt -> {
            String land = ComboValjLandID.getSelectedItem().toString();
            
            if (!land.equals("Välj land")) {
                String textValtLand = "Välj land: " + land;
                // Regex för att matcha siffran direkt efter "Välj avdelning: "
                Pattern pattern = Pattern.compile("Välj land: (\\d+)");
                Matcher matcher = pattern.matcher(textValtLand);
                
                if (matcher.find()) {
                    // Extrahera den första matchade gruppen
                    String enAvdelning = matcher.group(1);
                    lid = Integer.parseInt(enAvdelning);
                } else {
                    System.out.println("Ingen match hittades."); 
                }
            } 
        });
        try{
            String selectInfo = "select * from land where lid = " + lid + ";";
            ArrayList<HashMap<String, String>> info = idb.fetchRows(selectInfo);
            
            for(HashMap<String, String> enRad:info){
                for(String ettAttribut:enRad.keySet()){
                    switch(ettAttribut){
                        case "namn":
                            tfRedigeraNamn.setText(enRad.get(ettAttribut)); 
                            break;
                        case "sprak":
                            tfRedigeraSprak.setText(enRad.get(ettAttribut));
                            break;
                        case "valuta":
                            tfRedigeraValuta.setText(enRad.get(ettAttribut));
                            break;
                        case "tidszon":
                            tfRedigeraTidszon.setText(enRad.get(ettAttribut));
                            break;
                        case "politisk_struktur":
                            tfRedigeraPolitiskStruktur.setText(enRad.get(ettAttribut));
                            break;
                        case "ekonomi":
                            tfRedigeraEkonomi.setText(enRad.get(ettAttribut));
                            break;
                    }
                }
            }
        }
        catch(InfException ex){
            System.out.println(ex); 
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLaggTillEttLand = new javax.swing.JLabel();
        lblLyckat = new javax.swing.JLabel();
        tfRedigeraNamn = new javax.swing.JTextField();
        tfRedigeraSprak = new javax.swing.JTextField();
        tfRedigeraValuta = new javax.swing.JTextField();
        tfRedigeraTidszon = new javax.swing.JTextField();
        tfRedigeraPolitiskStruktur = new javax.swing.JTextField();
        tfRedigeraEkonomi = new javax.swing.JTextField();
        lblValutaFel = new javax.swing.JLabel();
        btnTillbaka = new javax.swing.JButton();
        btnSpara = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblLaggTillEttLand1 = new javax.swing.JLabel();
        ComboValjLandID = new javax.swing.JComboBox<>();
        lblLyckat1 = new javax.swing.JLabel();
        lblFelmeddelande = new javax.swing.JLabel();

        lblLaggTillEttLand.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLaggTillEttLand.setText("Redigera landets uppgifter");

        lblLyckat.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 2, 12)); // NOI18N
        lblLyckat.setForeground(new java.awt.Color(0, 153, 0));
        lblLyckat.setText("Ändringarna har sparats!");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblValutaFel.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 2, 12)); // NOI18N
        lblValutaFel.setForeground(new java.awt.Color(255, 0, 0));
        lblValutaFel.setText("Felaktigt format! Max nio siffror exklusive två decimaler");

        btnTillbaka.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        btnSpara.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        btnSpara.setText("Spara");
        btnSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jLabel1.setText("Välj land att redigera");

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jLabel2.setText("Namn");

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jLabel3.setText("Språk");

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jLabel4.setText("Valuta");

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jLabel5.setText("Tidszon");

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jLabel6.setText("Politisk Struktur");

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jLabel7.setText("Ekonomi");

        lblLaggTillEttLand1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        lblLaggTillEttLand1.setText("REDIGERA LAND");

        ComboValjLandID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboValjLandID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboValjLandIDActionPerformed(evt);
            }
        });

        lblLyckat1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 2, 12)); // NOI18N
        lblLyckat1.setForeground(new java.awt.Color(0, 153, 0));
        lblLyckat1.setText("Ändringarna har sparats!");

        lblFelmeddelande.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 2, 12)); // NOI18N
        lblFelmeddelande.setForeground(new java.awt.Color(255, 0, 0));
        lblFelmeddelande.setText("Alla fält måste fyllas i");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLaggTillEttLand1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFelmeddelande, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValutaFel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfRedigeraValuta, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfRedigeraSprak, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfRedigeraNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboValjLandID, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfRedigeraTidszon, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfRedigeraPolitiskStruktur, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfRedigeraEkonomi, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblLyckat1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnSpara)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnTillbaka))))
                                .addGap(0, 0, 0)))))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblLaggTillEttLand1)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ComboValjLandID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfRedigeraNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfRedigeraSprak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfRedigeraValuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(2, 2, 2)
                .addComponent(lblValutaFel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfRedigeraTidszon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfRedigeraPolitiskStruktur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfRedigeraEkonomi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTillbaka)
                    .addComponent(btnSpara)
                    .addComponent(lblFelmeddelande))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLyckat1)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        new AllaLander(idb, inloggadAnvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
    boolean hasError = false;
    boolean hittad = false;
    lblValutaFel.setVisible(false);
    lblLyckat1.setVisible(false);
    lblFelmeddelande.setVisible(false);

    try {
        String namn = tfRedigeraNamn.getText();
        String sprak = tfRedigeraSprak.getText();
        String textValuta = tfRedigeraValuta.getText();
        String tidszon = tfRedigeraTidszon.getText();
        String politiskStruktur = tfRedigeraPolitiskStruktur.getText();
        String ekonomi = tfRedigeraEkonomi.getText();

        //Kontrollera om textfält är tomma
        if (namn.isEmpty()) {
            lblFelmeddelande.setVisible(true); //Fel: namn kan inte vara tomt
            hasError = true;
        }
        if (sprak.isEmpty()) {
            lblFelmeddelande.setVisible(true); //Fel: språk kan inte vara tomt
            hasError = true;
        }
        if (tidszon.isEmpty()) {
            lblFelmeddelande.setVisible(true); //Fel: tidszon kan inte vara tomt
            hasError = true;
        }
        if (politiskStruktur.isEmpty()) {
            lblFelmeddelande.setVisible(true); //Fel: politisk struktur kan inte vara tomt
            hasError = true;
        }
        if (ekonomi.isEmpty()) {
            lblFelmeddelande.setVisible(true); //Fel: ekonomi kan inte vara tomt
            hasError = true;
        }

        //Kontrollera och hantera valuta
        try {
            if (!textValuta.isEmpty()) {
                enValuta = Double.parseDouble(textValuta);
            }
        } catch (NumberFormatException ex) {
            lblValutaFel.setVisible(true);
            hasError = true; 
        }

        //Om det finns fel - avbryt
        if (hasError) {
            return; //Hoppa över resten av koden om det finns fel
        }

        //Utför uppdatering om inga fel finns
        String valuta = String.valueOf(enValuta);
        String updateLand = "update land set namn = '" + namn + "', sprak = '" + sprak + "', valuta = " + valuta +
                            ", tidszon = '" + tidszon + "', politisk_struktur = '" + politiskStruktur + "', ekonomi = '" + ekonomi + "' where lid = " + lid + ";";
        idb.update(updateLand);
        lblLyckat1.setVisible(true);
    } catch (InfException ex) { 
        System.out.println(ex);
    } catch (NumberFormatException ex) {
        System.out.println(ex);
    }       
    }//GEN-LAST:event_btnSparaActionPerformed
  
    private void ComboValjLandIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboValjLandIDActionPerformed
        fyllTextfields();
    }//GEN-LAST:event_ComboValjLandIDActionPerformed

        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RedigeraLand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RedigeraLand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RedigeraLand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RedigeraLand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new RedigeraLand().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboValjLandID;
    private javax.swing.JButton btnSpara;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblFelmeddelande;
    private javax.swing.JLabel lblLaggTillEttLand;
    private javax.swing.JLabel lblLaggTillEttLand1;
    private javax.swing.JLabel lblLyckat;
    private javax.swing.JLabel lblLyckat1;
    private javax.swing.JLabel lblValutaFel;
    private javax.swing.JTextField tfRedigeraEkonomi;
    private javax.swing.JTextField tfRedigeraNamn;
    private javax.swing.JTextField tfRedigeraPolitiskStruktur;
    private javax.swing.JTextField tfRedigeraSprak;
    private javax.swing.JTextField tfRedigeraTidszon;
    private javax.swing.JTextField tfRedigeraValuta;
    // End of variables declaration//GEN-END:variables
}
