/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package systemvetenskapligaprojektet;
import java.util.ArrayList;
import oru.inf.InfDB; //Ska importeras till alla klasser
import oru.inf.InfException;
import java.math.BigDecimal;
import java.util.HashMap;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
/**
 *
 * @author lisas
 */
public class RedigeraAnsvarProjekt extends javax.swing.JFrame {
    private static InfDB idb;
    private String inloggadAnvandare;
    private double enKostnad;
    private int projektchef;
    private int land;
    private String projektID;
    private int ettProjektID;
    /**
     * Creates new form RedigeraAnsvarProjekt
     */
    public RedigeraAnsvarProjekt(InfDB idb, String inloggadAnvandare) {
        initComponents();
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        lblFelStartdatum.setVisible(false);
        lblFelSlutdatum.setVisible(false);
        lblFelKostnad.setVisible(false);
        lblFelStatus.setVisible(false);
        lblFelPrioritet.setVisible(false);
        lblFelProjektchef.setVisible(false);
        lblFelLand.setVisible(false);
        fyllComboBox(projektID);
    }
    
    private void fyllComboBox(String projektID){
        try{
        
        //Hämta projektID från projektchefen som är inloggad
        String selectPid = "SELECT pid, projektnamn FROM projekt where projektchef in (select aid from anstalld where epost = '" + inloggadAnvandare + "');";
        
        ArrayList<HashMap<String, String>> allaPid = idb.fetchRows(selectPid);
        
        ComboRedigeraProjekt.removeAllItems();
        ComboRedigeraProjekt.addItem("Välj projekt");
        
        for (HashMap<String, String> projekt : allaPid) {
                String projektInfo = projekt.get("pid") + " - " + projekt.get("projektnamn");
                ComboRedigeraProjekt.addItem(projektInfo);
            }
        }
        catch (InfException e) {
            JOptionPane.showMessageDialog(this, "Kunde inte fylla kopplade partners: " + e.getMessage());
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTillbaka = new javax.swing.JButton();
        btnSpara = new javax.swing.JButton();
        lblRedigeraProjektet = new javax.swing.JLabel();
        lblProjektnamn = new javax.swing.JLabel();
        lblBeskrivning = new javax.swing.JLabel();
        lblStartdatum = new javax.swing.JLabel();
        lblSlutdatum = new javax.swing.JLabel();
        lblKostnad = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblPrioritet = new javax.swing.JLabel();
        lblProjektchef = new javax.swing.JLabel();
        lblLand = new javax.swing.JLabel();
        tfProjektnamn = new javax.swing.JTextField();
        tfBeskrivning = new javax.swing.JTextField();
        tfStartdatum = new javax.swing.JTextField();
        tfSlutdatum = new javax.swing.JTextField();
        tfKostnad = new javax.swing.JTextField();
        tfStatus = new javax.swing.JTextField();
        tfPrioritet = new javax.swing.JTextField();
        tfProjektchef = new javax.swing.JTextField();
        tfLand = new javax.swing.JTextField();
        lblFelStartdatum = new javax.swing.JLabel();
        lblFelSlutdatum = new javax.swing.JLabel();
        lblFelKostnad = new javax.swing.JLabel();
        lblFelStatus = new javax.swing.JLabel();
        lblFelPrioritet = new javax.swing.JLabel();
        lblFelProjektchef = new javax.swing.JLabel();
        lblFelLand = new javax.swing.JLabel();
        ComboRedigeraProjekt = new javax.swing.JComboBox<>();
        tfID = new javax.swing.JTextField();
        lblFelID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        btnSpara.setText("Spara");
        btnSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaActionPerformed(evt);
            }
        });

        lblRedigeraProjektet.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRedigeraProjektet.setText("Redigera projektets uppgifter");

        lblProjektnamn.setText("Projektnamn");

        lblBeskrivning.setText("Beskrivning");

        lblStartdatum.setText("Startdatum");

        lblSlutdatum.setText("Slutdatum");

        lblKostnad.setText("Kostnad");

        lblStatus.setText("Status");

        lblPrioritet.setText("Prioritet");

        lblProjektchef.setText("Projektchef");

        lblLand.setText("Land");

        lblFelStartdatum.setText("Felaktigt datumformat!");

        lblFelSlutdatum.setText("Felaktigt datumformat!");

        lblFelKostnad.setText("Felaktigt format!");

        lblFelStatus.setText("Ange giltig status");

        lblFelPrioritet.setText("Ange giltig prioritet");

        lblFelProjektchef.setText("Ange giltigt projektchefID");

        lblFelLand.setText("Ange giltigt landID");

        ComboRedigeraProjekt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboRedigeraProjekt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComboRedigeraProjektMouseClicked(evt);
            }
        });
        ComboRedigeraProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboRedigeraProjektActionPerformed(evt);
            }
        });

        tfID.setText("jTextField1");

        lblFelID.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblLand, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblProjektchef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPrioritet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblKostnad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSlutdatum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblStartdatum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBeskrivning, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblProjektnamn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSpara, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTillbaka)
                                .addGap(81, 81, 81))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfProjektnamn, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                    .addComponent(tfBeskrivning)
                                    .addComponent(tfStartdatum)
                                    .addComponent(tfSlutdatum)
                                    .addComponent(tfKostnad)
                                    .addComponent(tfStatus)
                                    .addComponent(tfPrioritet)
                                    .addComponent(tfProjektchef)
                                    .addComponent(tfLand))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRedigeraProjektet)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFelStartdatum)
                                    .addComponent(lblFelSlutdatum)
                                    .addComponent(lblFelKostnad)
                                    .addComponent(lblFelStatus)
                                    .addComponent(lblFelPrioritet)
                                    .addComponent(lblFelProjektchef)
                                    .addComponent(lblFelLand)
                                    .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFelID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboRedigeraProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lblRedigeraProjektet))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(ComboRedigeraProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjektnamn)
                    .addComponent(tfProjektnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBeskrivning)
                    .addComponent(tfBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStartdatum)
                    .addComponent(tfStartdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFelStartdatum))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSlutdatum)
                    .addComponent(tfSlutdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFelSlutdatum))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKostnad)
                    .addComponent(tfKostnad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFelKostnad))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(tfStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFelStatus))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrioritet)
                    .addComponent(tfPrioritet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFelPrioritet))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjektchef)
                    .addComponent(tfProjektchef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFelProjektchef))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLand)
                    .addComponent(tfLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFelLand))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(lblFelID)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTillbaka)
                    .addComponent(btnSpara))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        new AnsvarProjekt(idb, inloggadAnvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
        boolean hasError = false;
        boolean hittad = false;
        try{
            if(!hasError){
                try{
                    String projektnamn = tfProjektnamn.getText();
                    String beskrivning = tfBeskrivning.getText();
                    String startdatum = tfStartdatum.getText();
                    String slutdatum = tfSlutdatum.getText();
                    String textKostnad = tfKostnad.getText();
                    String status = tfStatus.getText();
                    String prioritet = tfPrioritet.getText();
                    String textProjektchef = tfProjektchef.getText();
                    String textLand = tfLand.getText();
                    
                    if(!hasError){
                        try{
                            textProjektchef = tfProjektchef.getText();
                            projektchef = Integer.parseInt(textProjektchef);
                        }
                        catch(NumberFormatException ex){
                            lblFelProjektchef.setVisible(true);
                            hasError = true;
                        } 
                    }                 
                    if(!hasError){
                        try{
                            textLand = tfLand.getText();
                            land = Integer.parseInt(textLand);
                        }

                        catch(NumberFormatException ex){
                            lblFelLand.setVisible(true);
                            hasError = true;
                        }
                    }                   
                    BigDecimal kostnad;
                        try{
                            kostnad = new BigDecimal(textKostnad);
                
                            //Kontrollera (12, 2)
                            if(kostnad.precision() > 12 || kostnad.scale() > 2){
                                throw new NumberFormatException();
                            }
                        }
                        catch(NumberFormatException ex){
                            lblFelKostnad.setVisible(true);
                            return;
                        }
                        String selectAnsvarProjekt = "select * from projekt where pid = " + ettProjektID + ";";
                        HashMap<String, String> ettAnsvarProjekt = idb.fetchRow(selectAnsvarProjekt);
                        String enRad[] = new String[ettAnsvarProjekt.size()];
                        for(String ettAttribut:ettAnsvarProjekt.keySet()){
                            switch(ettAttribut){
                                case "pid":
                                    enRad[0] = ettAnsvarProjekt.get("pid");
                                    break;
                                case "projektnamn":
                                    enRad[1] = ettAnsvarProjekt.get("projektnamn");
                                    break;
                                case "beskrivning":
                                    enRad[2] = ettAnsvarProjekt.get("beskrivning");
                                    break;
                                case "startdatum":
                                    enRad[3] = ettAnsvarProjekt.get("startdatum");
                                    break;
                                case "slutdatum":
                                    enRad[4] = ettAnsvarProjekt.get("slutdatum");
                                    break;
                                case "kostnad":
                                    enRad[5] = ettAnsvarProjekt.get("kostnad");
                                    break;
                                case "status":
                                    enRad[6] = ettAnsvarProjekt.get("status");
                                    break;
                                case "prioritet":
                                    enRad[7] = ettAnsvarProjekt.get("prioritet");
                                    break;
                                case "projektchef":
                                    enRad[8] = ettAnsvarProjekt.get("projektchef");
                                    break;
                                case "land":
                                    enRad[9] = ettAnsvarProjekt.get("land");
                                    break;
                            }
                        }
                    if(projektnamn.isEmpty()){
                        projektnamn = enRad[1];
                    }
                    if(beskrivning.isEmpty()){
                       beskrivning = enRad[2];
                    }
                    if(startdatum.isEmpty()){
                       startdatum = enRad[3];
                    }
                    if(slutdatum.isEmpty()){
                       slutdatum = enRad[4];
                    }
                    if(textKostnad.isEmpty()){
                       textKostnad = enRad[5];
                    }
                    if(status.isEmpty()){
                       status = enRad[6];     
                    }
                    if(prioritet.isEmpty()){
                       prioritet = enRad[7];     
                    }  
                    if(textProjektchef.isEmpty()){
                       textProjektchef = enRad[8];     
                    }  
                    if(textLand.isEmpty()){
                       textLand = enRad[9];     
                    } 
                    
                String updateAnsvarProjekt = "update projekt set projektnamn = '" + projektnamn + "', beskrivning = '" + beskrivning + "', startdatum = '" + startdatum + "', slutdatum = '" + slutdatum + "', kostnad = " + kostnad + ", status = '" + status + "', prioritet = '" + prioritet + "', projektchef = " + projektchef + ", land = " + land + " where pid = " + ettProjektID + ";";
                    System.out.println(updateAnsvarProjekt);
                idb.update(updateAnsvarProjekt);
                new AnsvarProjekt(idb,inloggadAnvandare).setVisible(true);
                this.setVisible(false);
                }
                catch(InfException ex){ 
                    System.out.println(ex);
                }
            }
        }
        catch(NumberFormatException ex){ 
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnSparaActionPerformed


    
    private void fyllTextfields(){
        ComboRedigeraProjekt.addActionListener(evt -> {
            String projekt = ComboRedigeraProjekt.getSelectedItem().toString();
            

            if (!projekt.equals("Välj projekt")) {
                String textValtProjekt = "Välj projekt: " + projekt;
                System.out.println(textValtProjekt);
                // Regex för att matcha siffran direkt efter "Välj projekt: "
                Pattern pattern = Pattern.compile("Välj projekt: (\\d+)");
                Matcher matcher = pattern.matcher(textValtProjekt);

                // Kontrollera om mönstret hittades
                if (matcher.find()) {
                    // Extrahera den första matchade gruppen
                    String ettProjekt = matcher.group(1);
                    ettProjektID = Integer.parseInt(ettProjekt);
                    
                    System.out.println("Numret är: " + ettProjektID);
                } else {
                    System.out.println("Ingen match hittades."); 
                }
            } 
        });
        try{
            String selectInfo = "select * from projekt where pid = " + ettProjektID + ";";
            System.out.println(selectInfo);
            ArrayList<HashMap<String, String>> info = idb.fetchRows(selectInfo);
            
            for(HashMap<String, String> enRad:info){
                for(String ettAttribut:enRad.keySet()){
                    switch(ettAttribut){
                        case "projektnamn":
                            tfProjektnamn.setText(enRad.get(ettAttribut)); 
                            break;
                        case "beskrivning":
                            tfBeskrivning.setText(enRad.get(ettAttribut));
                            break;
                        case "startdatum":
                            tfStartdatum.setText(enRad.get(ettAttribut));
                            break;
                        case "slutdatum":
                            tfSlutdatum.setText(enRad.get(ettAttribut));
                            break;
                        case "kostnad":
                            tfKostnad.setText(enRad.get(ettAttribut));
                            break;
                        case "status":
                            tfStatus.setText(enRad.get(ettAttribut));
                            break;
                        case "prioritet":
                            tfPrioritet.setText(enRad.get(ettAttribut));
                            break;
                        case "projektchef":
                            tfProjektchef.setText(enRad.get(ettAttribut));
                            break;
                        case "land":
                            tfLand.setText(enRad.get(ettAttribut));
                            break;
                    }
                }
            }
        }
        catch(InfException ex){
            System.out.println(ex);
        }
    }
    
    private void ComboRedigeraProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboRedigeraProjektActionPerformed
         fyllTextfields();
    }//GEN-LAST:event_ComboRedigeraProjektActionPerformed

    private void ComboRedigeraProjektMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboRedigeraProjektMouseClicked
        

        
        //int valtProjekt = Integer.parseInt(valtPid[0]);
        //return valtProjekt;
    }//GEN-LAST:event_ComboRedigeraProjektMouseClicked
 
 
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RedigeraAnsvarProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RedigeraAnsvarProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RedigeraAnsvarProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RedigeraAnsvarProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            //    new RedigeraAnsvarProjekt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboRedigeraProjekt;
    private javax.swing.JButton btnSpara;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JLabel lblBeskrivning;
    private javax.swing.JLabel lblFelID;
    private javax.swing.JLabel lblFelKostnad;
    private javax.swing.JLabel lblFelLand;
    private javax.swing.JLabel lblFelPrioritet;
    private javax.swing.JLabel lblFelProjektchef;
    private javax.swing.JLabel lblFelSlutdatum;
    private javax.swing.JLabel lblFelStartdatum;
    private javax.swing.JLabel lblFelStatus;
    private javax.swing.JLabel lblKostnad;
    private javax.swing.JLabel lblLand;
    private javax.swing.JLabel lblPrioritet;
    private javax.swing.JLabel lblProjektchef;
    private javax.swing.JLabel lblProjektnamn;
    private javax.swing.JLabel lblRedigeraProjektet;
    private javax.swing.JLabel lblSlutdatum;
    private javax.swing.JLabel lblStartdatum;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextField tfBeskrivning;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfKostnad;
    private javax.swing.JTextField tfLand;
    private javax.swing.JTextField tfPrioritet;
    private javax.swing.JTextField tfProjektchef;
    private javax.swing.JTextField tfProjektnamn;
    private javax.swing.JTextField tfSlutdatum;
    private javax.swing.JTextField tfStartdatum;
    private javax.swing.JTextField tfStatus;
    // End of variables declaration//GEN-END:variables
}
