/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package systemvetenskapligaprojektet;
import oru.inf.InfDB; 
import oru.inf.InfException;
/**
 *
 * @author lisas
 */
public class TaBortPartner extends javax.swing.JFrame {

    private static InfDB idb;
    private String inloggadAnvandare;
    /**
     * Creates new form TaBortPartner
     */
    public TaBortPartner(InfDB idb, String inloggadAnvandare) {
        initComponents();
        this.inloggadAnvandare = inloggadAnvandare;
        this.idb = idb;
        lblFelIDTaBort.setVisible(false);
        lblTaBortPartnerLyckad.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTaBortPartner = new javax.swing.JLabel();
        tfTaBortID = new javax.swing.JTextField();
        lblTaBortPartnerLyckad = new javax.swing.JLabel();
        lblFelIDTaBort = new javax.swing.JLabel();
        btnTaBort = new javax.swing.JButton();
        btnTillbakaTaBort = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTaBortPartner.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTaBortPartner.setText("Ta bort en partner");

        tfTaBortID.setEditable(false);
        tfTaBortID.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        tfTaBortID.setForeground(new java.awt.Color(102, 102, 102));
        tfTaBortID.setText("Fyll i ID:t på den partner du önskar ta bort");
        tfTaBortID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfTaBortIDMouseClicked(evt);
            }
        });
        tfTaBortID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTaBortIDActionPerformed(evt);
            }
        });

        lblTaBortPartnerLyckad.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblTaBortPartnerLyckad.setForeground(new java.awt.Color(0, 153, 0));
        lblTaBortPartnerLyckad.setText("Partnern har tagits bort");

        lblFelIDTaBort.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblFelIDTaBort.setForeground(new java.awt.Color(255, 0, 0));
        lblFelIDTaBort.setText("ID:t finns inte i systemet");

        btnTaBort.setText("Ta bort");
        btnTaBort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortActionPerformed(evt);
            }
        });

        btnTillbakaTaBort.setText("Tillbaka");
        btnTillbakaTaBort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaTaBortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(lblTaBortPartner))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTaBortPartnerLyckad)
                            .addComponent(lblFelIDTaBort)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnTaBort)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnTillbakaTaBort))
                                .addComponent(tfTaBortID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblTaBortPartner)
                .addGap(18, 18, 18)
                .addComponent(tfTaBortID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTaBortPartnerLyckad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFelIDTaBort)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTaBort)
                    .addComponent(btnTillbakaTaBort))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfTaBortIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfTaBortIDMouseClicked
        tfTaBortID.setEditable(true);
        tfTaBortID.setText("");
    }//GEN-LAST:event_tfTaBortIDMouseClicked

    private void tfTaBortIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTaBortIDActionPerformed
        
    }//GEN-LAST:event_tfTaBortIDActionPerformed

    
    
    
    
    private void btnTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortActionPerformed
        try{
            String taBortPid = tfTaBortID.getText();
            int pid = Integer.parseInt(taBortPid);
        
            String kontrolleraPid = "select aid from anstalld where aid = " + pid + ";";
            String pidFinns = idb.fetchSingle(kontrolleraPid);
        
            if(pidFinns != null){
                String taBort = "delete from partner where pid = " + pid + ";";
                idb.delete(taBort); 
                lblTaBortPartnerLyckad.setVisible(true);
               }
               
            else{
                lblFelIDTaBort.setVisible(true);
            }
        }
        catch(InfException ex) {
            System.out.println(ex);
        }

        catch(NumberFormatException ex) {
            lblFelIDTaBort.setVisible(true);
        }
    }//GEN-LAST:event_btnTaBortActionPerformed

    
    
    private void btnTillbakaTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaTaBortActionPerformed
        new AllaPartners(idb,inloggadAnvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTillbakaTaBortActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaBortPartner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaBortPartner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaBortPartner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaBortPartner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new TaBortPartner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTaBort;
    private javax.swing.JButton btnTillbakaTaBort;
    private javax.swing.JLabel lblFelIDTaBort;
    private javax.swing.JLabel lblTaBortPartner;
    private javax.swing.JLabel lblTaBortPartnerLyckad;
    private javax.swing.JTextField tfTaBortID;
    // End of variables declaration//GEN-END:variables
}
