/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package systemvetenskapligaprojektet;
import oru.inf.InfDB; 
import oru.inf.InfException;
/**
 *
 * @author lisas
 */
public class TaBortPartner extends javax.swing.JFrame {

    private static InfDB idb;
    private String inloggadAnvandare;
    private int pid;
    /**
     * Creates new form TaBortPartner
     */
    public TaBortPartner(InfDB idb, String inloggadAnvandare) {
        initComponents();
        this.inloggadAnvandare = inloggadAnvandare;
        this.idb = idb;
        lblFelIDTaBort.setVisible(false);
        lblTaBortPartnerLyckad.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTaBortPartner = new javax.swing.JLabel();
        lblTaBortPartnerLyckad = new javax.swing.JLabel();
        lblFelIDTaBort = new javax.swing.JLabel();
        btnTaBort = new javax.swing.JButton();
        btnTillbakaTaBort = new javax.swing.JButton();
        tfTaBortID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTaBortPartner.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        lblTaBortPartner.setText("TA BORT EN PARTNER");

        lblTaBortPartnerLyckad.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 2, 12)); // NOI18N
        lblTaBortPartnerLyckad.setForeground(new java.awt.Color(0, 153, 0));
        lblTaBortPartnerLyckad.setText("Partnern har tagits bort!");

        lblFelIDTaBort.setFont(new java.awt.Font("Microsoft JhengHei UI", 2, 12)); // NOI18N
        lblFelIDTaBort.setForeground(new java.awt.Color(255, 0, 0));
        lblFelIDTaBort.setText("ID:t finns inte i systemet");

        btnTaBort.setText("Ta bort");
        btnTaBort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortActionPerformed(evt);
            }
        });

        btnTillbakaTaBort.setText("Tillbaka");
        btnTillbakaTaBort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaTaBortActionPerformed(evt);
            }
        });

        tfTaBortID.setEditable(false);
        tfTaBortID.setFont(new java.awt.Font("Microsoft JhengHei UI", 2, 12)); // NOI18N
        tfTaBortID.setForeground(new java.awt.Color(102, 102, 102));
        tfTaBortID.setText("Fyll i ID:t på den partner du önskar ta bort");
        tfTaBortID.setMinimumSize(new java.awt.Dimension(247, 32));
        tfTaBortID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfTaBortIDMouseClicked(evt);
            }
        });
        tfTaBortID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTaBortIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfTaBortID, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addComponent(lblTaBortPartner))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblFelIDTaBort, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnTaBort)
                                    .addGap(103, 103, 103)
                                    .addComponent(btnTillbakaTaBort))
                                .addComponent(lblTaBortPartnerLyckad, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblTaBortPartner)
                .addGap(18, 18, 18)
                .addComponent(tfTaBortID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFelIDTaBort)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTaBort)
                    .addComponent(btnTillbakaTaBort))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTaBortPartnerLyckad)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortActionPerformed
        try{
            lblFelIDTaBort.setVisible(false);
            lblTaBortPartnerLyckad.setVisible(false);
            String taBortPid = tfTaBortID.getText();
            try{
                pid = Integer.parseInt(taBortPid);
            }
            catch(NumberFormatException ex){
                System.out.println(ex);
            }
            String selectPid = "select pid from partner where pid = " + pid + ";";
            String pidFinns = idb.fetchSingle(selectPid);
        
            if(pidFinns != null){
                String selectProjekt_partner = "select pid from projekt_partner where partner_pid = " + pid + ";";
                String projekt_partner = idb.fetchSingle(selectProjekt_partner);
                if(projekt_partner != null){
                    String taBortProjekt_partner = "delete from projekt_partner where partner_pid = " + pid + ";";
                    idb.delete(taBortProjekt_partner);
                }
                String taBort = "delete from partner where pid = " + pid + ";";
                idb.delete(taBort);
                lblTaBortPartnerLyckad.setVisible(true);
            }              
            else{
                lblFelIDTaBort.setVisible(true);
            }
        }
        catch(InfException ex) {
            System.out.println(ex);
        }

        catch(NumberFormatException ex) {
            lblFelIDTaBort.setVisible(true);
        }
    }//GEN-LAST:event_btnTaBortActionPerformed

    private void btnTillbakaTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaTaBortActionPerformed
        new AllaPartners(idb,inloggadAnvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTillbakaTaBortActionPerformed

    private void tfTaBortIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfTaBortIDMouseClicked
        tfTaBortID.setEditable(true);
        tfTaBortID.setText("");
    }//GEN-LAST:event_tfTaBortIDMouseClicked

    private void tfTaBortIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTaBortIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTaBortIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaBortPartner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaBortPartner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaBortPartner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaBortPartner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new TaBortPartner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTaBort;
    private javax.swing.JButton btnTillbakaTaBort;
    private javax.swing.JLabel lblFelIDTaBort;
    private javax.swing.JLabel lblTaBortPartner;
    private javax.swing.JLabel lblTaBortPartnerLyckad;
    private javax.swing.JTextField tfTaBortID;
    // End of variables declaration//GEN-END:variables
}
